feat(#3): implement sandbox infrastructure
VilnaCRM-Org/website-infrastructure pull request #5
Opened 2024-06-26 09:29 UTC by YapieRT

As a front-end developer, I need to be able to create pull requests to the main branch and see my new features and fixes on the sandbox environment.

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING.md**](https://github.com/VilnaCRM-Org/infrastructure-template/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] You have only one commit (if not, squash them into one commit).

2024-07-03 02:37 UTC, YapieRT commented
Hi from GitHub CLI

2024-08-22 16:13 UTC, Kravalg commented
@coderabbitai full review

2024-08-23 12:18 UTC, Kravalg commented
@coderabbitai review

2024-09-02 23:04 UTC, Kravalg commented
@coderabbitai full review

2024-09-03 07:31 UTC, Kravalg commented
@coderabbitai full review

2024-09-03 11:29 UTC, bra1n2h commented
@coderabbitai full review

2024-09-03 20:49 UTC, Kravalg requested changes
Please follow the coderabbit comments and refactor the PR

2024-09-03 20:49 UTC, Kravalg commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  ]
Yeah, please suggest refactoring

2024-09-04 13:09 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/sandbox/data_s3.tf
> +}
What are the possible consequences of leaving current broader policies in place?

2024-09-04 16:01 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/data.tf
> +      "${aws_s3_bucket.bucket.arn}/*"
Are you sure about the bucket names, since the files you specified have different bucket names, yes, they have reports_bucket, but this is not the full name of the buckets?

2024-09-04 16:23 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  ]
I checked your change proposal and saw that you are using lambda function, what is this lambda function and what is it for?

2024-09-04 16:26 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  ]
@coderabbitai

2024-09-04 16:46 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Are you sure this is best practice since the blocks you added are deprecated?

2024-09-04 16:55 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
below is the code you recommended, but its usage is deprecated, are you sure it's worth adding?

lifecycle_rule {
id = "example"
enabled = true

transition {
days = 30
storage_class = "GLACIER"
}

expiration {
days = 90
}
}

logging {
target_bucket = "access-logs-bucket"
target_prefix = "log/"
}

versioning {
enabled = true
}

2024-09-05 11:59 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        Resource = "*"
yes, help please

2024-09-05 12:01 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        Resource = "*"
@coderabbitai

2024-09-05 12:18 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
I conducted my own analysis, here you can read: 
To help distribute management of S3 bucket settings as originally presented in #4418, the focus of this major milestone will be to deprecate (for the purpose of this release, this equates to marking previously configurable arguments as read-only /Computed and with a Deprecated message ) at least the following arguments (subject to change): lifecycle_rule, logging, versioning, replication_configuration, server_side_encryption_configuration. Independent resources for these arguments will include: aws_s3_bucket_lifecycle_configuration aws_s3_bucket_logging aws_s3_bucket_versioning aws_s3_bucket_replication_configuration aws_s3_bucket_server_side_encryption_configuration Data retention and security considerations are paramount when considering any form of alterations to the aws_s3_bucket resource, therefore upgrade documentation will be made readily available with the appropriate path to adoption of v4.0.0 of the provider.

2024-09-05 12:24 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Now try to apply these changes to my code according to the information I provided you.

2024-09-05 14:02 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        Resource = "*"
Are you confident that the resources listed cover all the required use cases for this role?
What are the potential risks of using the "*" character in my IAM policies?

2024-09-11 11:59 UTC, bra1n2h commented on README.md
> +
please review, i fixed this

2024-09-11 12:01 UTC, bra1n2h commented on aws/scripts/sh/sandbox_installation.sh
> +echo #### Install Software
that was resolved

2024-09-11 12:07 UTC, bra1n2h commented on aws/scripts/sh/sandbox_installation.sh
> +echo #### Install Software
resolved, check

2024-09-11 12:08 UTC, bra1n2h commented on aws/scripts/sh/website_installation.sh
> +n 20.14.0
Are you sure this is redundant installation?

2024-09-11 12:10 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/data.tf
> +      "${aws_s3_bucket.bucket.arn}/*"
review this, it should be resolved

2024-09-11 12:15 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/tfvars/prod.tfvars
> +project_name               = "website-test"
should be resolved, check please

2024-09-11 13:21 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/sandbox/data_general.tf
> +  }
If we want to allow the kms:CreateKey action, what resources can we specify to restrict, given that keys are created dynamically? How can we safely restrict key creation so that it complies with the principle of least privilege?

2024-09-11 13:22 UTC, bra1n2h commented on README.md
> +
that should be resolved already, check please

2024-09-11 14:33 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/sandbox/data_s3.tf
> +}
@Kravalg , I think this proposal is not suitable.

2024-09-11 15:45 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
>  }
check if resolved

2024-09-11 15:47 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/data.tf
> +      "${aws_s3_bucket.bucket.arn}/*"
@Kravalg , I'm not sure about this change

2024-09-11 15:54 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
>  }
@Kravalg , If you change the output name and description, you will get repeating code blocks, and if you change the value to a name instead of an ID, you will get an error (I have already tested this). What should I do in this case?

2024-09-11 15:58 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/outputs.tf
> +# This is where you put your outputs declaration
@Kravalg  , what do you think about this change?

2024-09-11 16:04 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/sandbox/data_general.tf
> +  }
@Kravalg , what do you think about this restricted approach?

2024-09-11 16:08 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
show me please this guidance

2024-09-11 16:38 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Show me the best practice for defining this variable and its further use based on the structure of this project.

2024-09-11 16:40 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Is this configuration i should add "abort_incomplete_multipart_upload" to follow best practise?

2024-09-11 17:48 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/kms.tf
> +}
@Kravalg , I checked the files that are related to this comment and I am not sure about the changes we need to make, I want you to pay attention to them as well

2024-09-11 20:36 UTC, Kravalg commented on terraform/app/modules/aws/iam/policies/sandbox/data_s3.tf
> +}
I agree with coderabbit, you need to follow at least privilege principle

2024-09-12 11:51 UTC, bra1n2h commented on aws/scripts/sh/sandbox_installation.sh
> +git clone -b $BRANCH_NAME "$WEBSITE_GIT_REPOSITORY_LINK.git" /codebuild-user/website
This comment should be resolved, check please

2024-09-12 11:52 UTC, bra1n2h commented on aws/scripts/sh/sandbox_installation.sh
> +cd /codebuild-user/website/
This comment should be resolved, check please

2024-09-12 11:54 UTC, bra1n2h commented on aws/scripts/sh/website_installation.sh
> +n 20.14.0
This comment should be resolved, check please

2024-09-12 11:54 UTC, bra1n2h commented on aws/scripts/sh/sandbox_deletion.sh
> +echo "Bucket $BUCKET_NAME was successfully deleted."
This comment should be resolved, check please

2024-09-12 11:54 UTC, bra1n2h commented on aws/scripts/sh/sandbox_deletion.sh
> +echo "Bucket $BUCKET_NAME was successfully deleted."
This comment should be resolved, check please

2024-09-12 11:55 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +fi
This comment should be resolved, check please

2024-09-12 11:55 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +fi
This comment should be resolved, check please

2024-09-12 11:55 UTC, bra1n2h commented on aws/buildspecs/sandbox/delete.yml
> +
This comment should be resolved, check please

2024-09-12 11:55 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/outputs.tf
> +}
This comment should be resolved, check please

2024-09-12 11:56 UTC, bra1n2h commented on aws/buildspecs/sandbox/up.yml
> +    - '**/*'
This comment should be resolved, check please

2024-09-12 11:56 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pull_request.sh'
This comment should be resolved, check please

2024-09-12 11:57 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/variables.tf
> +}
This comment should be resolved, check please

2024-09-12 11:57 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/policies.tf
> +
This comment should be resolved, check please

2024-09-12 11:57 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +fi
This comment should be resolved, check please

2024-09-12 11:57 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +    aws s3api put-bucket-policy --bucket "$PROJECT_NAME-$BRANCH_NAME" --policy file://s3_policy.json --region $AWS_DEFAULT_REGION
This comment should be resolved, check please

2024-09-12 11:57 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    create_s3_policy()
This comment should be resolved, check please

2024-09-12 11:57 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Policy has been written to s3_policy.json")
This comment should be resolved, check please

2024-09-12 11:58 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Config has been written to website_configuration.json")
This comment should be resolved, check please

2024-09-12 11:58 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/variables.tf
> +}
This comment should be resolved, check please

2024-09-12 11:58 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/tfvars/prod.tfvars
> +project_name               = "website-test"
This comment should be resolved, check please

2024-09-12 11:58 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  ]
This comment should be resolved, check please

2024-09-12 11:59 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
This comment should be resolved, check please

2024-09-12 11:59 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        Branch     = "3-implement-sandbox-infrastructure"
This comment should be resolved, check please

2024-09-12 11:59 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 11:59 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 12:00 UTC, bra1n2h commented on aws/scripts/sh/sandbox_installation.sh
> +cd /codebuild-user/website/
This comment should be resolved, check please

2024-09-12 12:00 UTC, bra1n2h commented on aws/scripts/sh/sandbox_installation.sh
> +git clone -b $BRANCH_NAME "$WEBSITE_GIT_REPOSITORY_LINK.git" /codebuild-user/website
This comment should be resolved, check please

2024-09-12 12:00 UTC, bra1n2h commented on aws/scripts/sh/sandbox_deletion.sh
> +echo "Bucket $BUCKET_NAME was successfully deleted."
This comment should be resolved, check please

2024-09-12 12:01 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
>  }
This comment should be resolved, check please

2024-09-12 12:01 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
>  }
This comment should be resolved, check please

2024-09-12 12:01 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
>  }
This comment should be resolved, check please

2024-09-12 12:02 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +fi
This comment should be resolved, check please

2024-09-12 12:02 UTC, bra1n2h commented on aws/buildspecs/sandbox/delete.yml
> +
This comment should be resolved, check please

2024-09-12 12:02 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/outputs.tf
> +}
This comment should be resolved, check please

2024-09-12 12:03 UTC, bra1n2h commented on aws/buildspecs/sandbox/up.yml
> +    - '**/*'
This comment should be resolved, check please

2024-09-12 12:03 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/main.tf
> +}
This comment should be resolved, check please

2024-09-12 12:03 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pull_request.sh'
This comment should be resolved, check please

2024-09-12 12:03 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/variables.tf
> +}
This comment should be resolved, check please

2024-09-12 12:03 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +fi
This comment should be resolved, check please

2024-09-12 12:04 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +    aws s3api put-bucket-policy --bucket "$PROJECT_NAME-$BRANCH_NAME" --policy file://s3_policy.json --region $AWS_DEFAULT_REGION
This comment should be resolved, check please

2024-09-12 12:04 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    create_s3_policy()
This comment should be resolved, check please

2024-09-12 12:04 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Policy has been written to s3_policy.json")
This comment should be resolved, check please

2024-09-12 12:04 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Config has been written to website_configuration.json")
This comment should be resolved, check please

2024-09-12 12:05 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/variables.tf
> +}
This comment should be resolved, check please

2024-09-12 12:05 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/tfvars/prod.tfvars
> +project_name               = "website-test"
This comment should be resolved, check please

2024-09-12 12:05 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 12:05 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 12:05 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 12:05 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 12:06 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +resource "aws_codebuild_project" "sandbox_deletion" {  #refactor (policies and resources)
This comment should be resolved, check please

2024-09-12 12:06 UTC, bra1n2h commented on aws/buildspecs/sandbox/delete.yml
> +      - ls -la
This comment should be resolved, check please

2024-09-12 12:06 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +fi
This comment should be resolved, check please

2024-09-12 12:07 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 12:07 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 12:07 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 12:07 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 12:07 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 12:07 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 12:08 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        Resource = "*"
This comment should be resolved, check please

2024-09-12 12:08 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
This comment should be resolved, check please

2024-09-12 12:08 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +fi
This comment should be resolved, check please

2024-09-12 12:09 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
This comment should be resolved, check please

2024-09-12 12:09 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
This comment should be resolved, check please

2024-09-12 12:09 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
This comment should be resolved, check please

2024-09-12 12:09 UTC, bra1n2h commented on aws/buildspecs/sandbox/delete.yml
> +      - echo "S3 bucket has been deleted."
This comment should be resolved, check please

2024-09-12 12:10 UTC, bra1n2h commented on aws/buildspecs/sandbox/delete.yml
> +
This comment should be resolved, check please

2024-09-12 12:12 UTC, bra1n2h commented on task/terraform_tests.yml
> +      - tfsec ./
We need this command, so if you dont have any other suggestions, check if i can resolve this comment

2024-09-12 12:15 UTC, bra1n2h commented on aws/scripts/sh/sandbox_deletion.sh
> +echo "Bucket $BUCKET_NAME was successfully deleted."
yes, proceed please

2024-09-12 13:04 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/policies.tf
> +
This comment should be resolved, check please

2024-09-12 13:04 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +fi
This comment should be resolved, check please

2024-09-12 13:11 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Policy has been written to s3_policy.json")
This comment should be resolved, check please

2024-09-12 13:11 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    create_s3_policy()
This comment should be resolved, check please

2024-09-12 13:17 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +    aws s3api put-bucket-policy --bucket "$PROJECT_NAME-$BRANCH_NAME" --policy file://s3_policy.json --region $AWS_DEFAULT_REGION
This comment should be resolved, check please

2024-09-12 13:18 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/tfvars/prod.tfvars
> +project_name               = "website-test"
This comment should be resolved, check please

2024-09-12 13:24 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +    aws s3api put-bucket-policy --bucket "$PROJECT_NAME-$BRANCH_NAME" --policy file://s3_policy.json --region $AWS_DEFAULT_REGION
@coderabbitai This comment should be resolved, check please

2024-09-12 13:25 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  ]
@coderabbitai This comment should be resolved, check please

2024-09-12 13:32 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  ]
This comment should be resolved, check please

2024-09-12 13:34 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        Branch     = "3-implement-sandbox-infrastructure"
This comment should be resolved, check please

2024-09-12 13:34 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 13:34 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 13:44 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 13:44 UTC, bra1n2h commented on aws/scripts/sh/sandbox_installation.sh
> +git clone -b $BRANCH_NAME "$WEBSITE_GIT_REPOSITORY_LINK.git" /codebuild-user/website
This comment should be resolved, check please

2024-09-12 14:12 UTC, bra1n2h commented on README.md
> +
I found just 1 blank before this sentece Install the [AWS CLI]. Check it please

2024-09-12 14:12 UTC, bra1n2h commented on aws/scripts/sh/sandbox_deletion.sh
> +echo "Bucket $BUCKET_NAME was successfully deleted."
This comment should be resolved, check please

2024-09-12 14:25 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
>  }
This comment should be resolved, check please

2024-09-12 14:26 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +fi
This comment should be resolved, check please

2024-09-12 14:30 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/outputs.tf
> +}
This comment should be resolved, check please

2024-09-12 14:30 UTC, bra1n2h commented on aws/buildspecs/sandbox/up.yml
> +    - '**/*'
This comment should be resolved, check please

2024-09-12 14:37 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/main.tf
> +}
This comment should be resolved, check please

2024-09-12 14:37 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +      - '. ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pull_request.sh'
This comment should be resolved, check please

2024-09-12 14:37 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/variables.tf
> +}
This comment should be resolved, check please

2024-09-12 14:38 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +    aws s3api put-bucket-policy --bucket "$PROJECT_NAME-$BRANCH_NAME" --policy file://s3_policy.json --region $AWS_DEFAULT_REGION
This comment should be resolved, check please

2024-09-12 14:45 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    create_s3_policy()
This comment should be resolved, check please

2024-09-12 14:45 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Policy has been written to s3_policy.json")
This comment should be resolved, check please

2024-09-12 14:45 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Config has been written to website_configuration.json")
This comment should be resolved, check please

2024-09-12 14:45 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/variables.tf
> +}
This comment should be resolved, check please

2024-09-12 15:01 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Policy has been written to s3_policy.json")
review this 1 more time, everything should be fine

2024-09-12 15:02 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Config has been written to website_configuration.json")
review this 1 more time, everything should be fine

2024-09-12 15:02 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/tfvars/prod.tfvars
> +project_name               = "website-test"
This comment should be resolved, check please

2024-09-12 15:02 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 15:10 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 15:10 UTC, bra1n2h commented on README.md
> +
This comment should be resolved, check please

2024-09-12 15:16 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +fi
This comment should be resolved, check please

2024-09-12 15:16 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 15:16 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 15:28 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 15:28 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 15:28 UTC, bra1n2h commented on aws/scripts/sh/sandbox_creation.sh
> +   if [ $? -ne 0 ]; then
This comment should be resolved, check please

2024-09-12 15:39 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        Resource = "*"
This comment should be resolved, check please

2024-09-12 15:41 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
This comment should be resolved, check please

2024-09-12 15:47 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        Resource = "*"
yes, i'm using correct arns for these resources

2024-09-12 15:49 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
yes, provide me detailed steps

2024-09-12 15:56 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
This comment should be resolved, check please

2024-09-12 15:56 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
This comment should be resolved, check please

2024-09-12 15:56 UTC, bra1n2h commented on aws/buildspecs/sandbox/delete.yml
> +      - echo "S3 bucket has been deleted."
This comment should be resolved, check please

2024-09-12 16:01 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
check please 1 more time, i added this block

2024-09-12 16:03 UTC, bra1n2h commented on aws/buildspecs/sandbox/delete.yml
> +
This comment should be resolved, check please

2024-09-12 18:27 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
Yes, they should grant only necessary permissions. Anything else i should change or i can resolve this comment?

2024-09-12 19:10 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
review i added this configuration

2024-09-13 11:49 UTC, bra1n2h commented on README.md
> +In case you are using any other region, please respecify it in the `tfvars`. Also specify your own domain name in the `tfvars`.
Check again, there should be an empty line between the text.

2024-09-13 11:52 UTC, bra1n2h commented on README.md
> +In case you are using any other region, please respecify it in the `tfvars`. Also specify your own domain name in the `tfvars`.
can i resolve this comment?

2024-09-13 11:54 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
same mistake, lifecycle_rule and versioning are deprecated

2024-09-13 11:56 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
check please, i think i refactored and resolved this

2024-09-13 12:00 UTC, bra1n2h commented on aws/scripts/sh/sandbox_deletion.sh
> +echo "Bucket $BUCKET_NAME was successfully deleted."
Check it should be resolved

2024-09-13 12:01 UTC, bra1n2h commented on aws/scripts/sh/sandbox_deletion.sh
> +echo "Bucket $BUCKET_NAME was successfully deleted."
check, it should be resolved

2024-09-13 12:17 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
I dont need additional changes, if you are sure that code fully meets best practice, then everything fine. Can i resolve this comment?

2024-09-13 12:29 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
> +  value       = aws_s3_bucket.bucket.id
i can't use  value       = aws_s3_bucket.bucket.name , what should i do to follow best practice in such situation?

2024-09-13 12:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
review please from your paw and make sure that i'm right

2024-09-13 12:34 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
> +  value       = aws_s3_bucket.bucket.id
So i'll continue use id. Can i close this comment?

2024-09-13 12:38 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
> +  description = "Name of the public bucket"
Review your comments we discussed that I can use ID

2024-09-13 12:44 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
>  }
I closed duplicated comments. I discussed with coderabbitai that we can use id here, but i also want to know your opinion

2024-09-13 14:16 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
When talking about authorized users, are you talking about Principals specified in the access policy?

2024-09-13 14:21 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
AWS services are listed in all principals

2024-09-13 14:27 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
can i resolve this comment?

2024-09-13 15:14 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
@Kravalg , should i add this sns configuration?

2024-09-13 15:24 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@Kravalg , what do you think about this request? We use this variable not only in this file, maybe i should use the same practice for whole files in this stack?

2024-09-13 15:38 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Policy has been written to s3_policy.json")
there is comma after brace, check this

2024-09-13 15:38 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Should be resolved, check please

2024-09-13 15:38 UTC, bra1n2h commented on aws/buildspecs/sandbox/delete.yml
> +
Should be resolved, check please

2024-09-13 15:38 UTC, bra1n2h commented on aws/buildspecs/sandbox/up.yml
> +
Should be resolved, check please

2024-09-13 15:47 UTC, bra1n2h commented on aws/buildspecs/sandbox/up.yml
> +    - '**/*'
Should be resolved, check please

2024-09-13 15:47 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +    print("Policy has been written to s3_policy.json")
Should be resolved, check please

2024-09-13 15:48 UTC, bra1n2h commented on aws/buildspecs/sandbox/delete.yml
> +
Should be resolved, check please

2024-09-13 15:48 UTC, bra1n2h commented on aws/buildspecs/sandbox/up.yml
> +    - '**/*'
Should be resolved, check please

2024-09-13 15:55 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
yes, help please

2024-09-13 16:18 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
show me how to refactor according best practice

2024-09-15 20:52 UTC, Kravalg commented on terraform/app/stacks/website-sandbox/outputs.tf
> +# This is where you put your outputs declaration
Coderabbit has a nice idea, please do this refactoring

2024-09-16 11:42 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
I removed these lines, do i need to make other changes?

2024-09-16 11:47 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
Are these notifications about all pipelines or about a specific one?

2024-09-16 12:54 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
can you please provide refactoring but sns should be for slack not for email

2024-09-16 13:06 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
@coderabbitai

2024-09-16 15:10 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/data.tf
> +      "${aws_s3_bucket.bucket.arn}/*"
Yes, these links are intentional

2024-09-16 15:18 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/data.tf
> +      "${aws_s3_bucket.bucket.arn}/*"
@coderabbitai

2024-09-16 15:28 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/data.tf
> +      "${aws_s3_bucket.bucket.arn}/*"
Is there something i need to refactor or i can resolve this conversation?

2024-09-16 15:32 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/data.tf
> +      "${aws_s3_bucket.bucket.arn}/*"
@coderabbitai

2024-09-16 15:40 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/kms.tf
> +}
@coderabbitai here is this doc, I think it doesn't use least privilige principle, check it please:
data "aws_iam_policy_document" "codepipeline_sns_kms_key_policy_doc" {
  statement {
    sid     = "EnableRootAccessAndPreventPermissionDelegationForCodePipelineSNSKMSKey"
    effect  = "Allow"
    actions = ["kms:*"]
    #checkov:skip=CKV_AWS_356:Without this statement, KMS key cannot be managed by root
    resources = ["${aws_kms_key.codepipeline_sns_encryption_key.arn}"]
    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${local.account_id}:root"]
    }
  }

2024-09-16 15:48 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/kms.tf
> +}
@coderabbitai

2024-09-16 18:20 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
should be resolved, check please

2024-09-16 18:20 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
should be resolved, check please

2024-09-16 18:21 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/sandbox/data_s3.tf
> +}
should be resolved, check please

2024-09-16 18:22 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
should be resolved, check please

2024-09-16 18:22 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
should be resolved, check please

2024-09-16 18:24 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/kms.tf
> +}
I checked and refactored policies according at least privilege principle, anything else?

2024-09-16 18:24 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/outputs.tf
> +# This is where you put your outputs declaration
@coderabbitai should be resolved, check please

2024-09-16 18:26 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/outputs.tf
>  }
@coderabbitai should be resolved, check please

2024-09-16 18:27 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/sandbox/data_s3.tf
> +}
@coderabbitai should be resolved, check please

2024-09-16 18:32 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai

2024-09-16 18:33 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/sandbox/data_general.tf
> +  }
@coderabbitai

2024-09-16 18:38 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/kms.tf
> +}
@coderabbitai

2024-09-17 18:14 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
review existing files, especially /website-infrastructure/terraform/app/modules/aws/chatbot/main.tf we already have chatbot. What can you say after reviewing this file, what is the best practice for adding notifications to slack

2024-09-17 18:20 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
@coderabbitai

2024-09-17 19:17 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
@coderabbitai should be resolved check please

2024-09-17 19:18 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/kms.tf
> +}
@coderabbitai should be resolved, check please

2024-09-17 19:18 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/sandbox/data_general.tf
> +  }
removed, check please

2024-09-18 14:01 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/outputs.tf
> +}
Yes, this one is correct, because the previous one gave an error

2024-09-18 14:03 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/outputs.tf
> +}
can i resolve this conversation?

2024-09-18 14:04 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/outputs.tf
> +# This is where you put your outputs declaration
Are you sure this is the best practice to leave this comment?

2024-09-18 14:06 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/outputs.tf
> +}
Don't you think this is not the best practice to have name as sandbox_bucket_name, and value as id?

2024-09-18 14:08 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/outputs.tf
> +}
can i resolve this conversation now?

2024-09-18 14:12 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/sandbox/data_general.tf
> +    resources = ["arn:aws:s3:::terraform-state-${local.account_id}-${var.region}-${var.environment}"]
It is defined like you suggested in locals block, everything fine

2024-09-18 14:50 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +        "sns.${var.region}.amazonaws.com"
it defined as a variable is this bad practice?

2024-09-18 14:51 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +      identifiers = ["arn:aws:iam::${local.account_id}:root"]
This variable defined in locals block

2024-09-18 15:08 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +  }
show me best practice how to define these variables

2024-09-18 15:09 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +  pipeline_type = "V2"
Why should i remove this attribute and explain why is it unsupported?

2024-09-18 15:10 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
Yes, i'm sure that this integration of an existing configuration, anything else i should change?

2024-09-18 15:11 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +  name     = "${var.project_name}-notifications"
Committable suggestion was skipped due to low confidence. explain me this sentence

2024-09-18 15:37 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +}
Show me example following best practices, how i can refactor this code

2024-09-18 16:02 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +        }
After i refactored code according to your suggestion i got this error message:
Invalid expression: Expected the start of an expression, but found an invalid expression token.

2024-09-18 16:06 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +        "${aws_sns_topic.codepipeline_notifications.arn}"
show me steps how should i add this locals following best practice

2024-09-18 17:33 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +        }
Here is also 1 more error message:
Missing argument separator: A comma is required to separate each function argument from the next

2024-09-18 17:40 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +        }
Still have this error: [{
	"resource": "/home/nikita/VSCODE-setup-codebuild/website-infrastructure/terraform/app/modules/aws/codepipeline/sandbox/main.tf",
	"owner": "HashiCorpTerraform",
	"severity": 8,
	"message": "Missing argument separator: A comma is required to separate each function argument from the next.",
	"source": "Terraform",
	"startLineNumber": 78,
	"startColumn": 7,
	"endLineNumber": 78,
	"endColumn": 8
}]

2024-09-18 18:05 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +        "${aws_sns_topic.codepipeline_notifications.arn}"
which lines should be updated?

2024-09-18 18:32 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/variables.tf
> +}
The given value is not suitable for module.sandbox_codepipeline.var.stages
[2024-09-18T21:30:55 #350282 terraspace validate ci-cd-infrastructure]: │ declared at ../../modules/aws/codepipeline/sandbox/variables.tf:56,1-18:
[2024-09-18T21:30:55 #350282 terraspace validate ci-cd-infrastructure]: │ incorrect list element type: object required.

2024-09-18 18:36 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/variables.tf
> +}
lets try list(map(any)), provide me this refactor please

2024-09-18 19:02 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +  pipeline_type = "V2"
I use env variables in this pipeline, that's why i need this attribute

2024-09-18 19:05 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +  pipeline_type = "V2"
yes, i need this line, anything else i can change or i can resolve this conversation?

2024-09-18 19:09 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/variables.tf
> +}
yes, this type is working fine, can i resolve this conversation?

2024-09-18 19:12 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +}
@Kravalg I think this is fine for us to use IAM instead of KMS, what do you think?

2024-09-18 19:13 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +data "aws_partition" "current" {}
@Kravalg , I'm not really sure about this changes

2024-09-18 19:14 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    #checkov:skip=CKV_AWS_356:Without this statement, KMS key cannot be managed by root
@Kravalg what about this skipped checkov security check?

2024-09-19 12:22 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +  name     = "${var.project_name}-notifications"
Check please, should be resolved

2024-09-19 12:23 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/outputs.tf
> +# This is where you put your outputs declaration
Check please, should be resolved

2024-09-19 12:23 UTC, bra1n2h commented on terraform/app/modules/aws/chatbot/outputs.tf
> +}
Check please, should be resolved

2024-09-19 12:35 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/variables.tf
> +}
Check please, should be resolved

2024-09-19 12:35 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/variables.tf
> +}
Check please, should be resolved

2024-09-19 12:36 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +        "${aws_sns_topic.codepipeline_notifications.arn}"
Check please, should be resolved

2024-09-19 12:36 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +      "kms:Decrypt"
Check please, should be resolved

2024-09-19 12:40 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    actions   = ["kms:*"]
Check please, should be resolved

2024-09-19 12:40 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +  }
Check please, should be resolved

2024-09-19 13:46 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/locals.tf
> +}
show me correct format

2024-09-19 13:50 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +}
show me correct format

2024-09-19 13:56 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
Show me correct format

2024-09-19 14:06 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
are you sure that variables are in right place?

2024-09-19 17:32 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
I need GitHub token and you are right I need to store it in secret manager, but also I need to have script for token rotation. Can you help me to implement this according to project infrastructure and following best practices

2024-09-19 18:07 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
you have nice idea, but let's make it more suitable for this project. 
We have python scripts along this path: /website-infrastructure/aws/lambda/python
Same thing with zip archives: /website-infrastructure/aws/lambda/zip
Also as i can see you updated role just in sandbox_deletion, can you make research through files what roles should be updated as this one?

2024-09-20 11:26 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/sandbox/data_general.tf
> +  }
@coderabbitai, i removed it, check please

2024-09-20 11:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +  description = "ARN of existing SNS topics for Chatbot"
Should be resolved, check please

2024-09-20 11:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +  description = "List of Map containing information about the stages of the Sandbox CodePipeline"
Should be resolved, check please

2024-09-20 11:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +  description = "Unique name for this SandBox Codepipeline"
Should be resolved, check please

2024-09-20 11:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +  description = "Buildspecs of Sandbox Deploy"
Should be resolved, check please

2024-09-20 11:38 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
check format for this file, is it good now?

2024-09-20 11:39 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/locals.tf
> +}
Should be resolved, check please

2024-09-20 11:56 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
I run this command, but also i want you to check from your hand

2024-09-20 15:01 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
@coderabbitai first of all check this file /website-infrastructure/terraform/app/stacks/ci-cd-infrastructure/chatbot.tf we have notifications for different situations and pipelines, what did you suggest add notifications for?
I think we have notifications which cover all pipelines, if i'm not right explain me

2024-09-20 15:41 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
@coderabbitai Then let's do the cleanup and remove unnecessary variables and modules, that were added for this slack notifications feature

2024-09-20 19:14 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
Are you sure there is circular dependency? As we just put arn into codepipeline_role_arn variable

2024-09-20 19:15 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  detect_changes = "false"
we have github triggers to detect changes in our code

2024-09-22 16:34 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  depends_on = [module.sandbox_codebuild, module.sandbox_s3_artifacts_bucket]
by adding this i encounter such issue:
[2024-09-22T18:28:09 #36196 terraspace validate ci-cd-infrastructure]: │ Error: Cycle: module.sandbox_s3_artifacts_bucket.var.tags (expand), module.sandbox_s3_artifacts_bucket.var.project_name (expand), module.sandbox_codepipeline_iam_role.aws_iam_role_policy_attachment.codepipeline_policy_role_attachment, module.sandbox_codepipeline_iam_role.aws_iam_policy.codepipeline_policy, module.sandbox_s3_artifacts_bucket.output.arn (expand), module.sandbox_codepipeline_iam_role.var.s3_bucket_arn (expand), module.sandbox_codepipeline_iam_role.data.aws_iam_policy_document.codepipeline_policy_document, module.sandbox_codepipeline_iam_role (close), module.sandbox_s3_artifacts_bucket (expand), module.sandbox_s3_artifacts_bucket.aws_s3_bucket.codepipeline_bucket

2024-09-22 16:45 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  depends_on = [module.sandbox_codebuild, module.sandbox_s3_artifacts_bucket]
Sorry, this issue not relevant to this comment. Let's continue this discussion until I figure out if this comment helps me or not.

2024-09-22 16:45 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +
by adding this i encounter such issue:
[2024-09-22T18:28:09 #36196 terraspace validate ci-cd-infrastructure]: │ Error: Cycle: module.sandbox_s3_artifacts_bucket.var.tags (expand), module.sandbox_s3_artifacts_bucket.var.project_name (expand), module.sandbox_codepipeline_iam_role.aws_iam_role_policy_attachment.codepipeline_policy_role_attachment, module.sandbox_codepipeline_iam_role.aws_iam_policy.codepipeline_policy, module.sandbox_s3_artifacts_bucket.output.arn (expand), module.sandbox_codepipeline_iam_role.var.s3_bucket_arn (expand), module.sandbox_codepipeline_iam_role.data.aws_iam_policy_document.codepipeline_policy_document, module.sandbox_codepipeline_iam_role (close), module.sandbox_s3_artifacts_bucket (expand), module.sandbox_s3_artifacts_bucket.aws_s3_bucket.codepipeline_bucket

2024-09-22 16:47 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
check, i changed it, should be resolved

2024-09-22 16:49 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +
can i resolve this conversation and leave code as it is?

2024-09-22 16:54 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
Format is correct now, can i resolve this conversation?

2024-09-22 16:55 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +}
Format is correct now, can i resolve this conversation?

2024-09-22 16:56 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/main.tf
> +}
Format is correct now, can i resolve this conversation?

2024-09-22 17:23 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  detect_changes = "false"
So can i resolve this conversation then?

2024-09-23 12:22 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
If I don't add this line, an error occurs that it will not be possible to update the key policy in the future.

2024-09-23 12:25 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
But if i keep as it is, i have this error message:
Error: waiting for KMS Key Policy (38603e2e-7f7d-4819-b30a-3772864cb663) policy update: operation error KMS: GetKeyPolicy, https response error StatusCode: 400, RequestID: 5d99566c-a317-4a78-a1e7-d81bad67cd2f, api error AccessDeniedException: User: arn:aws:iam::010438498391:user/sandbox-admin is not authorized to perform: kms:GetKeyPolicy on resource: arn:aws:kms:eu-central-1:010438498391:key/38603e2e-7f7d-4819-b30a-3772864cb663 because no resource-based policy allows the kms:GetKeyPolicy action.

2024-09-23 12:34 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
What if this user has AdministratorAccess Policy attached?

2024-09-23 12:41 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
What would you say about this policy attached to sandbox-admin?
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "AllowKMSFullAccess",
			"Effect": "Allow",
			"Action": [
				"kms:DescribeKey",
				"kms:GetKeyPolicy",
				"kms:PutKeyPolicy",
				"kms:List*",
				"kms:Encrypt",
				"kms:Decrypt",
				"kms:ReEncrypt*",
				"kms:GenerateDataKey*"
			],
                            <Correct resource statement>
		}
	]
}

2024-09-23 12:55 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
I added policy that you suggested and this policy includes such actions: actions = [
      "kms:GetKeyPolicy",
      "kms:PutKeyPolicy"
    ]
    
But i encountered a new erorr message:
Error: reading KMS Key (f78f033f-5b85-4039-980f-ee629aef8049): reading KMS Key (f78f033f-5b85-4039-980f-ee629aef8049) rotation enabled: operation error KMS: GetKeyRotationStatus, https response error StatusCode: 400, RequestID: b228073d-ca53-464e-96f4-f6f40597be32, api error AccessDeniedException: User: arn:aws:iam::010438498391:user/sandbox-admin is not authorized to perform: kms:GetKeyRotationStatus on resource: arn:aws:kms:eu-central-1:010438498391:key/f78f033f-5b85-4039-980f-ee629aef8049 because no resource-based policy allows the kms:GetKeyRotationStatus action

2024-09-23 13:52 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
What other errors can occur based on the same principle?

2024-09-23 15:25 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +}
@coderabbitai i have question about 1st step, i should refactor this file /website-infrastructure/terraform/app/modules/aws/codepipeline/sandbox/kms.tf there are 2 resources in this file: aws_kms_key and aws_kms_key_policy. Should i replace both with code that you provided in step 1?

2024-09-23 16:50 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
I have studied and understood that you have offered me 2 different ways to change this file, this one we are discussing and here is another one: Consider Using IAM Policies Instead of Key Policies. Let's choose the one that is the most secure and best practice.

2024-09-23 17:05 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +}
We discussed in another comment, that using  IAM instead of Key Policies isn't secure. Also you recommended this approach Modify the KMS Key Policy to Grant Permissions. What can you say, should i resolve this conversation and continue refactor according this approach "Modify the KMS Key Policy to Grant Permissions"?

2024-09-23 17:11 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +}
@coderabbitai

2024-09-23 17:15 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +}
@coderabbitai, let's get this clear, you said that AWS recommends using Key policies, please approve this, and then we'll continue to improve code quality. I want you to be ensure on your words

2024-09-23 17:26 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +}
Okay, so can I resolve this conversation and continue refactoring following your recommendations for changing the key policies?

2024-09-23 17:31 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +}
@coderabbitai

2024-09-23 18:29 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
statement {
    sid    = "AllowSandboxAdminFullAccess"
    effect = "Allow"
    actions = [
      "kms:DescribeKey",
      "kms:GetKeyPolicy",
      "kms:PutKeyPolicy",
      "kms:GetKeyRotationStatus",
    ]
    resources = ["${aws_kms_key.codepipeline_sns_encryption_key.arn}"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${local.account_id}:user/sandbox-admin"]
    }
  }
  this statement works great, what can you say about it, from the point of view of the principle of least privilege

2024-09-23 19:39 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +resource "aws_iam_role_policy" "codepipeline_restricted_access" {
you can check it should be resolved

2024-09-23 19:41 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +          "arn:aws:codepipeline:${var.region}:${local.account_id}:sandbox-pipeline-deletion"
yes, this variable is defined, can i resolve this conversation?

2024-09-23 19:42 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        ]
should be resolved check please

2024-09-23 19:42 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
should be resolved check please

2024-09-23 19:42 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +      },
should be resolved check please

2024-09-23 19:42 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
should be resolved check please

2024-09-23 19:46 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
should be resolved check please

2024-09-23 19:46 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
should be resolved check please

2024-09-23 19:55 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/data_kms.tf
> +    ]
yes, you can check previous comment where we discussed, that i need this key policies, becaues i encountered error without it. Error message was: it will not be possible to update the key policy in the future

2024-10-02 10:53 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +        "SCRIPT_DIR"                  = var.script_dir,
Please check if this comment can be resolved?

2024-10-02 11:02 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +
according to the project structure and best practice where would be better to add this variable?

2024-10-02 12:23 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  ]
Here is your previous comment:

Add explicit dependencies to avoid resource creation issues

In the sandbox_s3_artifacts_bucket module, you're referencing outputs from module.sandbox_codepipeline_kms and module.sandbox_codepipeline_iam_role which are defined later in the file. To ensure proper resource creation order, it's recommended to add explicit depends_on statements.

I'm trainee devops engineer, why did you ask to add these statements into depends_on block and now you ask me to remove them? Describe me everything

2024-10-02 12:32 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  ]
So, now following the best practice it is better to remove these statements from this block, right?

2024-10-02 12:59 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
show me please example

2024-10-02 21:29 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
We dont need KMS keys here, can i resolve this conversation?

2024-10-02 21:31 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Amazon S3 now applies server-side encryption with Amazon S3 managed keys (SSE-S3) as the base level of encryption for every bucket in Amazon S3. Starting January 5, 2023, all new object uploads to Amazon S3 are automatically encrypted at no additional cost and with no impact on performance.
Due to provided information can i resolve this conversation?

2024-10-02 21:31 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Amazon S3 now applies server-side encryption with Amazon S3 managed keys (SSE-S3) as the base level of encryption for every bucket in Amazon S3. Starting January 5, 2023, all new object uploads to Amazon S3 are automatically encrypted at no additional cost and with no impact on performance.
Due to provided information can i resolve this conversation?

2024-10-02 21:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  codestar_connection_arn = module.codestar_connection.arn
Yes, this module is defined, but you can verify this also

2024-10-02 21:38 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +        "SCRIPT_DIR"                  = var.script_dir,
Should be good now, can i resolve this conversation?

2024-10-02 21:41 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +}
sorry, my mistake, let's keep as you suggested before

2024-10-02 21:53 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  codepipeline_iam_role_name = "${var.sandbox_project_name}-codepipeline-role"
check please where we can use this variable, maybe you are right and we need this suffix to follow better flexibility

2024-10-03 11:18 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
Show me the required configuration so that you don't write later that there are errors in the configuration

2024-10-03 11:48 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
review existing iam policy for codebuild role, i'm sure that we can use it for this bucket

2024-10-03 11:57 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  codepipeline_iam_role_name = "${var.sandbox_project_name}-codepipeline-role"
I tried to add this variable, terraform says that it is not expected here

2024-10-03 12:11 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  codepipeline_iam_role_name = "${var.sandbox_project_name}-codepipeline-role"
I dont really think that we need to use this suffix, beacause we will use it only in one place within all stacks

2024-10-03 12:16 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +        }
This comment is kind duplicated, because next your comment suggests to use this variable in a separate block

2024-10-03 12:19 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +        }
This is not really duplicate comment, but you suggested to add comma and then remove this variable to a separate block

2024-10-03 12:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Is this problem resolved or not?

2024-10-03 20:09 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +}
Check please, should be good now

2024-10-03 20:10 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +        }
Check please, should be good now

2024-10-03 20:10 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
Check please, should be good now

2024-10-03 20:10 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Check please, should be good now

2024-10-03 20:11 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
check please did i resolve circular dependency?

2024-10-03 20:11 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
check please did i resolve circular dependency?

2024-10-04 10:10 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
what about variable IS_PULL_REQUEST, it also should be in lowercase?

2024-10-04 10:50 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
you can review that these variables are related to another file, for example /website-infrastructure/terraform/app/modules/aws/codepipeline/sandbox/main.tf  , so do you still think this is a good idea to change them?

2024-10-04 11:15 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        ]
what's wrong with 190-194?

2024-10-04 11:18 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        ]
Review please whole file 1 more time. And show me every line that you want to change

2024-10-04 13:22 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
I've tried to remove  the depends_on block from sandbox_codepipeline_iam_role, but pipeline doesn't work as expected. What are the possible options to resolve this circular dependencies?

2024-10-04 15:09 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        ]
should be resolved, check please

2024-10-04 15:09 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
should be resolved, check please

2024-10-04 15:09 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
should be resolved, check please

2024-10-04 15:09 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
should be resolved, check please

2024-10-04 15:11 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +  type        = string
you comment says: LGTM: New variable for sandbox buildspecs with minor suggestion

The addition of the sandbox_buildspecs variable is well-defined and provides a way to specify buildspecs for Sandbox Deployment. For consistency with other similar variables, consider updating the description to "Buildspecs of Sandbox Deployment".

Apply this minor change for consistency:

-  description = "Buildspecs for Sandbox Deployment"
+  description = "Buildspecs of Sandbox Deployment"


So what suggestion should i follow to satisfy you?

2024-10-04 16:24 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
This KMS is for S3 right? i dont need to use KMS because s3 has encryption by default. If we remove this kms will it help to resolve circular dependency?

2024-10-04 16:31 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
yes, help me to remove this KMS key to resolve circular dependency, but as the context check not only this file, because removing module and kms_key_arn variables will cause an error

2024-10-04 16:37 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
At the moment there is only 1 file for the sandbox removal function is sandbox_deletion. You asked me to remove hardcoded buckets names from this file and use variables. Where would be better to define bucket names?
We dont define bucket names in tfvars file. You can check them

2024-10-04 16:40 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
If i remove kms_key_arn from modules there will be error, modules, where it was defined, need this variable

2024-10-04 17:04 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
I'll use your last approach before file refactoring. I'll define these variables in the same file.

2024-10-04 17:09 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
Is this a good approach to set variable value null? Because it looks like a crutch

2024-10-04 17:20 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
so, let's return to the main question, this approach will resolve circular dependency?

2024-10-04 17:43 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
i tried to define them like this:  variable "sandbox_access_logs_bucket_name" {
  default = "${var.project_name}-sandbox-access-logs-${var.environment}"
}

variable "codepipeline_artifacts_bucket_name" {
  default = "${var.project_name}-codepipeline-artifacts-${var.environment}"
}
 but now i face error:[2024-10-04T20:37:02 #247201 terraspace init ci-cd-infrastructure]: │ Error: Variables not allowed

2024-10-04 17:50 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
Error: No value for required variable
[2024-10-04T20:48:20 #253888 terraspace plan ci-cd-infrastructure]: │ 
[2024-10-04T20:48:20 #253888 terraspace plan ci-cd-infrastructure]: │   on variables.tf line 263:
[2024-10-04T20:48:20 #253888 terraspace plan ci-cd-infrastructure]: │  263: variable "codepipeline_artifacts_bucket_name" {
[2024-10-04T20:48:20 #253888 terraspace plan ci-cd-infrastructure]: │ 
[2024-10-04T20:48:20 #253888 terraspace plan ci-cd-infrastructure]: │ The root module input variable "codepipeline_artifacts_bucket_name" is not
[2024-10-04T20:48:20 #253888 terraspace plan ci-cd-infrastructure]: │ set, and has no default value. Use a -var or -var-file command line
[2024-10-04T20:48:20 #253888 terraspace plan ci-cd-infrastructure]: │ argument to provide a value for this variable.
[2024-10-04T20:48:20 #253888 terraspace plan ci-cd-infrastructure]: ╵

2024-10-04 18:03 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    location  = "https://github.com/VilnaCRM-Org/website-infrastructure"
should be resolved

2024-10-04 19:24 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +
Why do I need to add this block of code, if buckets have encryption by default?

2024-10-04 22:16 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        OAuthToken = var.GITHUB_TOKEN
This comment is duplicated because we already have opened comment where we discussed about GitHub token, you can check

2024-10-07 13:20 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
review please this code, does it follow best practice and resolve circular dependency?
data "aws_s3_bucket" "sandbox_s3_artifacts_bucket" {
  bucket = module.sandbox_s3_artifacts_bucket.bucket
}

data "aws_kms_key" "sandbox_codepipeline_kms" {
  key_id = module.sandbox_codepipeline_kms.arn
}

data "aws_iam_role" "sandbox_codepipeline_iam_role" {
  name = module.sandbox_codepipeline_iam_role.role_name
}

module "sandbox_s3_artifacts_bucket" {
  source = "../../modules/aws/s3/codepipeline"

  project_name = var.sandbox_project_name
  region      = var.region
  environment = var.environment

  s3_artifacts_bucket_files_deletion_days = var.s3_artifacts_bucket_files_deletion_days

  kms_key_arn = data.aws_kms_key.sandbox_codepipeline_kms.arn

  codepipeline_role_arn = module.sandbox_codepipeline_iam_role.role_arn

  tags = var.tags
}

module "sandbox_codepipeline_kms" {
  source = "../../modules/aws/kms"

  codepipeline_role_arn = data.aws_iam_role.sandbox_codepipeline_iam_role.arn

  tags = var.tags
}

module "sandbox_codepipeline_iam_role" {
  source = "../../modules/aws/iam/roles/sandbox-codepipeline-role"

  project_name = var.sandbox_project_name
  codepipeline_iam_role_name = "${var.sandbox_project_name}-codepipeline-role"
  source_repo_owner = var.source_repo_owner
  source_repo_name = var.source_repo_name

  region = var.region
  environment = var.environment

  kms_key_arn = data.aws_kms_key.sandbox_codepipeline_kms.arn
  s3_bucket_arn = data.aws_s3_bucket.sandbox_s3_artifacts_bucket.arn
  codestar_connection_arn = module.codestar_connection.arn

  policy_arns = module.sandbox_policies.policy_arns

  tags = var.tags

  depends_on = [module.sandbox_policies]
}

module "sandbox_codebuild" {
  source = "../../modules/aws/codebuild/stages"

  project_name = var.sandbox_project_name
  build_projects = local.sandbox_build_projects

  s3_bucket_name = data.aws_s3_bucket.sandbox_s3_artifacts_bucket.bucket
  role_arn = data.aws_iam_role.sandbox_codepipeline_iam_role.arn
  kms_key_arn = data.aws_kms_key.sandbox_codepipeline_kms.arn

  region = var.region
  environment = var.environment

  tags = var.tags

  depends_on = [
    module.sandbox_s3_artifacts_bucket,
    module.sandbox_codepipeline_iam_role,
  ]
}

module "sandbox_codepipeline" {
  source = "../../modules/aws/codepipeline/sandbox"

  project_name = var.sandbox_project_name

  source_repo_owner = var.source_repo_owner
  source_repo_name = var.source_repo_name
  source_repo_branch = var.source_repo_branch

  IS_PULL_REQUEST = var.IS_PULL_REQUEST
  PR_NUMBER = var.PR_NUMBER
  BRANCH_NAME = var.BRANCH_NAME

  detect_changes = false

  stages = var.sandbox_stage_input

  region = var.region

  s3_bucket_name = data.aws_s3_bucket.sandbox_s3_artifacts_bucket.bucket
  codepipeline_role_arn = data.aws_iam_role.sandbox_codepipeline_iam_role.arn
  kms_key_arn = data.aws_kms_key.sandbox_codepipeline_kms.arn
  codestar_connection_arn = module.codestar_connection.arn

  tags = var.tags

  depends_on = [
    module.sandbox_codebuild,
    module.sandbox_s3_artifacts_bucket
  ]
}

2024-10-07 14:00 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
locals {
  project_name = var.sandbox_project_name
  region       = var.region
  account_id   = data.aws_caller_identity.current.account_id
}

module "sandbox_s3_artifacts_bucket" {
  source = "../../modules/aws/s3/codepipeline"

  project_name = local.project_name
  region       = local.region
  environment  = var.environment

  s3_artifacts_bucket_files_deletion_days = var.s3_artifacts_bucket_files_deletion_days

  kms_key_arn           = "arn:aws:kms:${local.region}:${local.account_id}:key/${module.sandbox_codepipeline_kms.key_id}"
  codepipeline_role_arn = "${local.project_name}-codepipeline-role"

  tags = var.tags
}

module "sandbox_codepipeline_kms" {
  source = "../../modules/aws/kms"

  codepipeline_role_arn = "${local.project_name}-codepipeline-role"

  tags = var.tags
}

module "sandbox_codepipeline_iam_role" {
  source = "../../modules/aws/iam/roles/sandbox-codepipeline-role"

  project_name            = local.project_name
  codepipeline_iam_role_name = "${local.project_name}-codepipeline-role"
  source_repo_owner       = var.source_repo_owner
  source_repo_name        = var.source_repo_name

  region      = local.region
  environment = var.environment

  kms_key_arn             = "arn:aws:kms:${local.region}:${local.account_id}:key/${module.sandbox_codepipeline_kms.key_id}"
  s3_bucket_arn           = "arn:aws:s3:::${module.sandbox_s3_artifacts_bucket.bucket}"
  codestar_connection_arn  = "arn:aws:codestar-connections:${local.region}:${local.account_id}:connection/${module.codestar_connection.id}"

  policy_arns = module.sandbox_policies.policy_arns

  tags = var.tags

  depends_on = [module.sandbox_policies]
}

module "sandbox_codebuild" {
  source = "../../modules/aws/codebuild/stages"

  project_name   = local.project_name
  build_projects = local.sandbox_build_projects

  s3_bucket_name = module.sandbox_s3_artifacts_bucket.bucket
  role_arn       = "${local.project_name}-codepipeline-role"
  kms_key_arn    = "arn:aws:kms:${local.region}:${local.account_id}:key/${module.sandbox_codepipeline_kms.key_id}"

  region      = local.region
  environment = var.environment

  tags = var.tags

  depends_on = [
    module.sandbox_s3_artifacts_bucket,
    module.sandbox_codepipeline_iam_role,
  ]
}

module "sandbox_codepipeline" {
  source = "../../modules/aws/codepipeline/sandbox"

  project_name = local.project_name

  source_repo_owner  = var.source_repo_owner
  source_repo_name   = var.source_repo_name
  source_repo_branch = var.source_repo_branch

  IS_PULL_REQUEST = var.IS_PULL_REQUEST
  PR_NUMBER       = var.PR_NUMBER
  BRANCH_NAME     = var.BRANCH_NAME

  detect_changes = false

  stages = var.sandbox_stage_input

  region = local.region

  s3_bucket_name          = module.sandbox_s3_artifacts_bucket.bucket
  codepipeline_role_arn   = "${local.project_name}-codepipeline-role"
  kms_key_arn             = "arn:aws:kms:${local.region}:${local.account_id}:key/${module.sandbox_codepipeline_kms.key_id}"
  codestar_connection_arn  = "arn:aws:codestar-connections:${local.region}:${local.account_id}:connection/${module.codestar_connection.id}"

  tags = var.tags

  depends_on = [module.sandbox_codebuild, module.sandbox_s3_artifacts_bucket]
}

I used your 1st suggestion to construct arns manually, how does it look for you?

2024-10-07 15:08 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
I refactored code according your suggestions, but there is still some promlems, help me please. Here are they:
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ Error: Unsupported attribute
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ 
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │   on sandbox.tf line 15, in module "sandbox_s3_artifacts_bucket":
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │   15:   kms_key_arn           = "arn:aws:kms:${local.region}:${local.account_id}:key/${module.sandbox_codepipeline_kms.key_id}"
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │     ├────────────────
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │     │ module.sandbox_codepipeline_kms is a object
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ 
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ This object does not have an attribute named "key_id".
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: ╵
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: ╷
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ Error: Unsupported attribute
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ 
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │   on sandbox.tf line 40, in module "sandbox_codepipeline_iam_role":
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │   40:   kms_key_arn             = "arn:aws:kms:${local.region}:${local.account_id}:key/${module.sandbox_codepipeline_kms.key_id}"
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │     ├────────────────
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │     │ module.sandbox_codepipeline_kms is a object
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ 
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ This object does not have an attribute named "key_id".
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: ╵
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: ╷
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ Error: Unsupported attribute
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ 
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │   on sandbox.tf line 42, in module "sandbox_codepipeline_iam_role":
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │   42:   codestar_connection_arn  = "arn:aws:codestar-connections:${local.region}:${local.account_id}:connection/${module.codestar_connection.id}"
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │     ├────────────────
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │     │ module.codestar_connection is a object
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ 
[2024-10-07T18:08:01 #134683 terraspace validate ci-cd-infrastructure]: │ This object does not have an attribute named "id".

2024-10-07 15:22 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
locals {
  project_name = var.sandbox_project_name
  region       = var.region
}

module "sandbox_s3_artifacts_bucket" {
  source = "../../modules/aws/s3/codepipeline"

  project_name = local.project_name
  region       = local.region
  environment  = var.environment

  s3_artifacts_bucket_files_deletion_days = var.s3_artifacts_bucket_files_deletion_days

  kms_key_arn           = module.sandbox_codepipeline_kms.arn
  codepipeline_role_arn = "arn:aws:iam::${local.account_id}:role/${local.project_name}-codepipeline-role"

  tags = var.tags
}

module "sandbox_codepipeline_kms" {
  source = "../../modules/aws/kms"

  codepipeline_role_arn = "arn:aws:iam::${local.account_id}:role/${local.project_name}-codepipeline-role"

  tags = var.tags
}

module "sandbox_codepipeline_iam_role" {
  source = "../../modules/aws/iam/roles/sandbox-codepipeline-role"

  project_name            = local.project_name
  codepipeline_iam_role_name = "${local.project_name}-codepipeline-role"
  source_repo_owner       = var.source_repo_owner
  source_repo_name        = var.source_repo_name

  region      = local.region
  environment = var.environment

  kms_key_arn             = module.sandbox_codepipeline_kms.arn
  s3_bucket_arn           = "arn:aws:s3:::${module.sandbox_s3_artifacts_bucket.bucket}"
  codestar_connection_arn = module.codestar_connection.arn

  policy_arns = module.sandbox_policies.policy_arns

  tags = var.tags

  depends_on = [module.sandbox_policies]
}

module "sandbox_codebuild" {
  source = "../../modules/aws/codebuild/stages"

  project_name   = local.project_name
  build_projects = local.sandbox_build_projects

  s3_bucket_name = module.sandbox_s3_artifacts_bucket.bucket
  role_arn       = "arn:aws:iam::${local.account_id}:role/${local.project_name}-codepipeline-role"
  kms_key_arn    = module.sandbox_codepipeline_kms.arn

  region      = local.region
  environment = var.environment

  tags = var.tags

  depends_on = [
    module.sandbox_s3_artifacts_bucket,
    module.sandbox_codepipeline_iam_role,
  ]
}

module "sandbox_codepipeline" {
  source = "../../modules/aws/codepipeline/sandbox"

  project_name = local.project_name

  source_repo_owner  = var.source_repo_owner
  source_repo_name   = var.source_repo_name
  source_repo_branch = var.source_repo_branch

  IS_PULL_REQUEST = var.IS_PULL_REQUEST
  PR_NUMBER       = var.PR_NUMBER
  BRANCH_NAME     = var.BRANCH_NAME

  detect_changes = false

  stages = var.sandbox_stage_input

  region = local.region

  s3_bucket_name          = module.sandbox_s3_artifacts_bucket.bucket
  codepipeline_role_arn   = "arn:aws:iam::${local.account_id}:role/${local.project_name}-codepipeline-role"
  kms_key_arn             = module.sandbox_codepipeline_kms.arn
  codestar_connection_arn = module.codestar_connection.arn

  tags = var.tags

  depends_on = [module.sandbox_codebuild, module.sandbox_s3_artifacts_bucket]
}

should be good now, what about circular dependency?

2024-10-07 15:25 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
I already have account_id, but not here, any other suggestions?

2024-10-07 15:28 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +}
why do i need to add it if i already have it and can use it?

2024-10-07 15:29 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
this approach looks good, but let's use github actions instead of python script

2024-10-07 17:42 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
is there anything you want to change same way?

2024-10-07 19:29 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
this should be resolved

2024-10-07 19:29 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
Should be resolved

2024-10-07 19:29 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
Should be resolved

2024-10-07 19:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  codepipeline_role_arn   = "arn:aws:iam::${local.account_id}:role/${local.project_name}-codepipeline-role"
are you sure, because we tried to resolve circular dependency with this approach?

2024-10-07 19:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  codepipeline_role_arn = "arn:aws:iam::${local.account_id}:role/${local.project_name}-codepipeline-role"
are you sure, because we tried to resolve circular dependency with this approach?

2024-10-07 19:34 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    ]
Are you sure we need to hardcode it?

2024-10-07 19:37 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  s3_bucket_arn           = "arn:aws:s3:::${module.sandbox_s3_artifacts_bucket.bucket}"
are you sure, because we tried to resolve circular dependency with this approach?

2024-10-07 19:37 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  role_arn       = "arn:aws:iam::${local.account_id}:role/${local.project_name}-codepipeline-role"
are you sure, because we tried to resolve circular dependency with this approach?

2024-10-07 19:47 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    ]
I think we can leave it as it is, because we have such permissions:
              "cloudwatch:EnableAlarmActions",
             "cloudwatch:DisableAlarmActions"
For codebuild and codepipeline and this is acceptable in my opinion, What do you think?

2024-10-07 19:49 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    ]
Let me know your opinion, i want to hear it

2024-10-07 19:59 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    ]
I got your point and reviewed configuration. Thank you for bringing up my attention, i'll refactor this code block

2024-10-07 21:50 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +  description = "Buildspecs for Website"
is there anything else that needs to be refactored?

2024-10-07 21:54 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +  description = "Buildspecs for Website"
i didn't get what do you mean "Group Slack Notification Variables"? Explain me this please

2024-10-07 22:00 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +  description = "Buildspecs for Website"
as i can see variables are already grouped

2024-10-08 11:27 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +  description = "Buildspecs for Website"
Also look at all the other descriptions, is there anything else that needs to be refactored?

2024-10-08 11:44 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
you can review file /website-infrastructure/terraform/app/modules/aws/codestar/data.tf . I already have codestar connection

2024-10-08 13:34 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
I tried to use this approach but the problem is that the pipeline is not created

2024-10-08 14:03 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
I encountered error that module undeclared in root directroy, i resolved it by adding this block in sandbox_deletion.tf file 
data "aws_codestarconnections_connection" "github_connection" {
  name = var.github_connection_name
}
Is this a good approach?
Also after i added this block i got this error, should i resolve it or adding this block in current file is not a good approach?
Unable to use Connection: arn:aws:codeconnections:eu-central-1:010438498391:connection/5c81808e-3c35-49d8-b89b-80a80f596fc9. The provided role does not have sufficient permissions.

2024-10-08 16:11 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
The only times it gets created is when a module is specified in the same file or a new codestar connection is created, any ideas?

2024-10-08 16:42 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
i need to assume policy to my codepipeline-role-sandbox-deletion in the proper way help me to do this, because i faced this error: Unable to use Connection: arn:aws:codeconnections:eu-central-1:010438498391:connection/5c81808e-3c35-49d8-b89b-80a80f596fc9. The provided role does not have sufficient permissions.

2024-10-08 17:48 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
after i added this iam role policy i faced this error: [GitHub] Upload to S3 failed with the following error: User: arn:aws:sts::010438498391:assumed-role/codepipeline-role-sandbox-deletion/1728407279215 is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::website-test-codepipeline-artifacts-test/sandbox-pipeline-del/source_out/GGY1pi4" because no identity-based policy allows the s3:PutObject action (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 4P0N1HZ90JGJVGT1; S3 Extended Request ID: CYLeZ1PtwCpvOQJVKG7CU/kxg4E5CrNa9xor6BzX+OrrTRuhE681tY7sJT+GSrC1bXruc/+jF9k=; Proxy: null) (Service: null; Status Code: 0; Error Code: null; Request ID: null; S3 Extended Request ID: null; Proxy: null)
I didn't have this error before i added this role policy

2024-10-08 18:12 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
let's discuss this problem first: [GitHub] Upload to S3 failed with the following error: User: arn:aws:sts::010438498391:assumed-role/codepipeline-role-sandbox-deletion/1728407279215 is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::website-test-codepipeline-artifacts-test/sandbox-pipeline-del/source_out/GGY1pi4" because no identity-based policy allows the s3:PutObject action (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 4P0N1HZ90JGJVGT1; S3 Extended Request ID: CYLeZ1PtwCpvOQJVKG7CU/kxg4E5CrNa9xor6BzX+OrrTRuhE681tY7sJT+GSrC1bXruc/+jF9k=; Proxy: null) (Service: null; Status Code: 0; Error Code: null; Request ID: null; S3 Extended Request ID: null; Proxy: null)

if i use variables in resource section i encounter this error, but if i hardcode it like this: "arn:aws:s3:::website-test-codepipeline-artifacts-test",
"arn:aws:s3:::website-test-codepipeline-artifacts-test/*"
 There is no such error, help me find out what can be problem in, review sandbox_deletion.tf file

2024-10-08 19:02 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
[GitHub] Unable to use Connection: arn:aws:codeconnections:eu-central-1:010438498391:connection/5c81808e-3c35-49d8-b89b-80a80f596fc9. The provided role does not have sufficient permissions. I resolved previous error, but i still encounter this error. What are the possible solutions?

2024-10-08 19:28 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
i defined resource like this but the problem still exists "arn:aws:codestar-connections:eu-central-1:010438498391:connection/5c81808e-3c35-49d8-b89b-80a80f596fc9"

2024-10-08 19:36 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
Everything is okay, but i dont have depends_on block. I'll add it and i'll inform you

2024-10-08 19:47 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
while i'm testing it you can check whole updated file and tell me what do you think
locals {
  sandbox_access_logs_bucket_name    = "${var.project_name}-sandbox-access-logs-${var.environment}"
  codepipeline_artifacts_bucket_name = "${var.project_name}-codepipeline-artifacts-${var.environment}"
  codebuild_logs_bucket_name         = "${var.project_name}-codebuild-logs-bucket-${var.environment}"
}

resource "aws_iam_role_policy" "codepipeline_restricted_access" {
  name = "codepipeline-restricted-access-policy"
  role = aws_iam_role.codepipeline_role_sandbox.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "codepipeline:StartPipelineExecution",
          "codepipeline:PutJobSuccessResult",
          "codepipeline:PutJobFailureResult",
          "codepipeline:GetPipelineState",
          "codepipeline:GetPipelineExecution",
          "codepipeline:GetPipeline",
          "codepipeline:ListPipelineExecutions",
          "codepipeline:ListPipelines"
        ]
        Resource = [
          "${aws_codepipeline.sandbox_pipeline.arn}"
        ]
      },
      {
        Effect = "Allow"
        Action = [
          "codebuild:StartBuild",
          "codebuild:BatchGetBuilds",
          "codebuild:ListBuilds",
          "codebuild:ListProjects",
          "codebuild:BatchGetProjects"
        ]
        Resource = [
          "${aws_codebuild_project.sandbox_deletion.arn}"
        ]
      },
      {
        Effect = "Allow"
        Action = [
          "s3:PutObject",
          "s3:GetObject",
          "s3:ListBucket",
          "s3:DeleteObject"
        ]
        Resource = [
          "arn:aws:s3:::website-test-codepipeline-artifacts-test",
          "arn:aws:s3:::website-test-codepipeline-artifacts-test/*"
        ]
      }
    ]
  })
}

resource "aws_codebuild_project" "sandbox_deletion" {
  name         = "sandbox-deletion"
  service_role = aws_iam_role.codebuild_role_sandbox.arn

  source {
    type      = "GITHUB"
    location  = "https://github.com/${var.source_repo_owner}/${var.source_repo_name}"
    buildspec = var.buildspec_path
  }

  environment {
    compute_type = "BUILD_GENERAL1_SMALL"
    image        = "aws/codebuild/standard:7.0"
    type         = "LINUX_CONTAINER"
  }

  logs_config {
    s3_logs {
      status   = "ENABLED"
      location = aws_s3_bucket.codebuild_logs_bucket.arn
    }
  }

  artifacts {
    type = "NO_ARTIFACTS"
  }
}

data "aws_codestarconnections_connection" "github_connection" {
  name = var.github_connection_name
}

resource "aws_iam_role_policy" "codepipeline_codestar_connection_policy" {
  name = "codepipeline-codestar-connection-policy"
  role = aws_iam_role.codepipeline_role_sandbox.name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = "codestar-connections:UseConnection"
        Resource = "arn:aws:codestar-connections:eu-central-1:010438498391:connection/5c81808e-3c35-49d8-b89b-80a80f596fc9"
      }
    ]
  })
}

resource "aws_codepipeline" "sandbox_pipeline" {
  name     = "sandbox-pipeline-deletion"
  role_arn = aws_iam_role.codepipeline_role_sandbox.arn
  #checkov:skip=CKV_AWS_219:CodePipeline Artifact store does not need a KMS CMK
  artifact_store {
    type     = "S3"
    location = aws_s3_bucket.codepipeline_bucket.bucket
  }

  stage {
    name = "Source"

    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"
      output_artifacts = ["source_output"]

      configuration = {
        ConnectionArn    = data.aws_codestarconnections_connection.github_connection.arn
        FullRepositoryId = "${var.source_repo_owner}/${var.source_repo_name}"
        BranchName       = var.source_repo_branch
      }
    }
  }

  stage {
    name = "Build"

    action {
      name             = "Build"
      category         = "Build"
      owner            = "AWS"
      provider         = "CodeBuild"
      version          = "1"
      input_artifacts  = ["source_output"]
      output_artifacts = ["build_output"]

      configuration = {
        ProjectName = aws_codebuild_project.sandbox_deletion.name
      }
    }
  }

  depends_on = [
    aws_codestarconnections_connection.github_connection
  ]
}

resource "aws_iam_role" "codepipeline_role_sandbox" {
  name = "codepipeline-role-sandbox-deletion"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "codepipeline.amazonaws.com"
        }
      }
    ]
  })
}

resource "aws_iam_role" "codebuild_role_sandbox" {
  name = "codebuild-role-sandbox-deletion"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "codebuild.amazonaws.com"
        }
      }
    ]
  })
}

resource "aws_iam_policy" "codebuild_s3_access_policy" {
  name        = "codebuild-s3-access-policy-sandbox"
  description = "Policy to allow CodeBuild to access S3"

  depends_on = [
    aws_s3_bucket.codepipeline_bucket,
    aws_s3_bucket.codebuild_logs_bucket,
  ]

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3:GetObject",
          "s3:PutObject",
          "s3:ListBucket",
          "s3:DeleteObject"
        ]
        Resource = [
          "arn:aws:s3:::website-test-codepipeline-artifacts-test",
          "arn:aws:s3:::website-test-codepipeline-artifacts-test/*",
          "${aws_s3_bucket.codebuild_logs_bucket.arn}",
          "${aws_s3_bucket.codebuild_logs_bucket.arn}/*"
        ]
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "codebuild_s3_access_policy_attachment" {
  role       = aws_iam_role.codebuild_role_sandbox.id
  policy_arn = aws_iam_policy.codebuild_s3_access_policy.arn
}

resource "aws_iam_role_policy" "codebuild_cloudwatch_logs_access" {
  name = "codebuild-cloudwatch-logs-access-policy-sandbox"
  role = aws_iam_role.codebuild_role_sandbox.id

  policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Effect = "Allow",
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ],
        Resource = [
          "arn:aws:logs:${var.region}:${local.account_id}:log-group:/aws/codebuild/${aws_codebuild_project.sandbox_deletion.name}",
          "arn:aws:logs:${var.region}:${local.account_id}:log-group:/aws/codebuild/${aws_codebuild_project.sandbox_deletion.name}:*"
        ]
      }
    ]
  })
}

resource "aws_s3_bucket" "access_logs_bucket" {
  #checkov:skip=CKV_AWS_145:The KMS encryption of access logs bucket is not needed
  #checkov:skip=CKV2_AWS_62:The event notifications of access logs bucket is not needed
  #checkov:skip=CKV_AWS_144:The S3 bucket cross-region replication is not needed
  bucket = local.sandbox_access_logs_bucket_name

  tags = {
    Name = "sandbox-deletion-access-logs-bucket"
  }
}

resource "aws_s3_bucket_public_access_block" "access_logs_bucket_public_access_block" {
  bucket                  = aws_s3_bucket.access_logs_bucket.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_lifecycle_configuration" "access_logs_bucket_lifecycle" {
  bucket = aws_s3_bucket.access_logs_bucket.id

  rule {
    id     = "log-expiration"
    status = "Enabled"

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }

    transition {
      days          = 90
      storage_class = "GLACIER"
    }

    expiration {
      days = 365
    }
  }
}

resource "aws_s3_bucket_versioning" "access_logs_bucket_versio [...]

2024-10-08 20:00 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
yes, the problem Unable to use Connection: arn:aws:codeconnections:eu-central-1:010438498391:connection/5c81808e-3c35-49d8-b89b-80a80f596fc9. The provided role does not have sufficient permissions. Still exists

2024-10-08 20:08 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
I've already provided you whole code and you can check that i already have this IAM role with necessary permissions

2024-10-08 20:11 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
yes, i have everything, but problem still exists Unable to use Connection: arn:aws:codeconnections:eu-central-1:010438498391:connection/5c81808e-3c35-49d8-b89b-80a80f596fc9. The provided role does not have sufficient permissions.

2024-10-08 20:21 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    }
I already have comment where we discuss how to implement it, so i'll close this comment

2024-10-08 23:46 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +    ]
you can check i removed

2024-10-08 23:46 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +  description = "Buildspecs for Website"
you can check i resolved

2024-10-08 23:56 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
why should i remove location, won't it cause any errors?

2024-10-09 00:06 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
@coderabbitai

2024-10-09 00:17 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
@coderabbitai won't it cause any errors if i remove this location variable?

2024-10-09 00:25 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
this comment is not good, i won't refactor code according it

2024-10-09 17:46 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
I'll need to use this token in script along this path /website-infrastructure/aws/scripts/sh/create_pull_request.sh
Also, i think it would be better to create separate IAM following best practice so tell me What would be the best way to distribute these resources across files according to this infrastructure?

2024-10-09 18:07 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
I wrote this infrastructure and want you to check it:
for IAM:
# IAM Policy Document for GitHub Actions
data "aws_iam_policy_document" "github_actions_assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["github.com"]
    }
  }
}

# IAM Role for GitHub Actions
resource "aws_iam_role" "github_actions_role" {
  name               = "github-actions-role"
  assume_role_policy = data.aws_iam_policy_document.github_actions_assume_role_policy.json
}

# IAM Policy for accessing Secrets Manager
resource "aws_iam_policy" "github_actions_policy" {
  name   = "github-actions-policy"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect    = "Allow"
        Action    = [
          "secretsmanager:GetSecretValue",
          "secretsmanager:PutSecretValue",
          "secretsmanager:DescribeSecret"
        ]
        Resource = aws_secretsmanager_secret.github_token.arn
      },
    ]
  })
}

# Attach the policy to the role
resource "aws_iam_role_policy_attachment" "github_actions_attachment" {
  role       = aws_iam_role.github_actions_role.name
  policy_arn = aws_iam_policy.github_actions_policy.arn
}

For secret manager:
resource "aws_secretsmanager_secret" "github_token" {
  name        = var.github_token_secret_name
  description = "GitHub token for CodePipeline"
}
also i added this line to bash script in create_pull_request file
# Retrieve GitHub token from AWS Secrets Manager
    GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id your-secret-name --query SecretString --output text | jq -r '.token')
    
what do you think? 
github rotation yml without changes is similar to yours

2024-10-09 18:14 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
help me with refactoring, if we have github actions for token rotation how it would be better to assign proper permissions?

2024-10-09 20:39 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Let's check if i get it right along this path create new stack directory and files for role and variables /website-infrastructure/terraform/app/modules/aws/iam/roles
variables just these or i need to have 2 files for variables?
variable "github_org" {
  description = "GitHub organization name"
  type        = string
}

variable "github_repo" {
  description = "GitHub repository name"
  type        = string
}

variable "github_branch" {
  description = "GitHub branch name for the workflow"
  type        = string
}

variable "github_token_secret_name" {
  description = "Name of the GitHub token secret in AWS Secrets Manager"
  type        = string
}
for policies this path: /website-infrastructure/terraform/app/modules/aws/iam/policies

2024-10-09 20:47 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
Show me steps i should follow after i added files for IAM role, IAM policy, variables file and github workflow file?
variables file i added in the directory where IAM role file located also

2024-10-09 20:54 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
got it, we did all necessary steps for modules, but what about Reference Modules in Stack?

2024-10-09 21:05 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
I'm talking about modules that we added for github rotation, should we add reference for them in stacks?

2024-10-09 21:11 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
sorry, i dont need to use it in this pipeline, what in that case?

2024-10-09 21:15 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
what about reference modules for token rotation in stacks if we won't use the token in pipeline?

2024-10-09 23:18 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
you didn't get it right i mean reference modules that related to github rotation token do we need add refernce in stack?

2024-10-09 23:22 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
why do you talk about lambda since we use GitHub  Actions instead of python?

2024-10-09 23:59 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
you have lost the context of our dialogue. Let me describe everything for you. 
i'll add role along this path /website-infrastructure/terraform/app/modules/aws/iam/roles/github_rotation_token_role/main.tf
i'll add variables along this path /website-infrastructure/terraform/app/modules/aws/iam/roles/github_rotation_token_role/variables.tf
i'll add policy along this path /website-infrastructure/terraform/app/modules/aws/iam/oidc/github_rotation_token_policy/main.tf
I'll need you to add additional steps that i need:
describe me aws_secret_manager that i need to add to store token
describe me which stack it would be better to define these modules in
also you how and where it would be better to attach policy to role?
all these steps should follow best practices

2024-10-10 00:04 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
okay, but what about outputs to attach policy to proper role we need to create outputs file, right?

2024-10-11 13:24 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
you also suggested to remove temporary file at all, so tell me what approach follows best practice?

2024-10-11 13:30 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
@coderabbitai

2024-10-11 13:36 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai i removed github token and also added files for github rotation, you can check

2024-10-11 16:38 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai

2024-10-11 16:50 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai I'm talking about this resource codepipeline_role_policy_attachment location 
modules/aws/iam/roles/codepipeline-role in policy-attachment file, is it a good way to define this resource right here?

2024-10-11 17:25 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
wait, let's review it is module reference to attach policies, i think we dont need to create it at all, because policies are being attached directly from the resource: resource "aws_iam_role_policy_attachment" "github_token_policy_attachment" {
  role       = "sandbox-test-codepipeline-role"
  policy_arn = aws_iam_policy.github_token_policy.arn
}
do you agree with me?

2024-10-11 17:27 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai

2024-10-11 17:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai i renamed this module to the proper one it is github_token_policy_attachment, but i didn't find any other similar module, i just found resources in modules/aws dirs? 
It seems that i don't need to create it here, what do you think?

2024-10-11 17:37 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai let me know your opinion too, what do you think about it?
But i'm pretty sure that i'm right

2024-10-11 17:46 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
i renamed this module to the proper one it is github_token_policy_attachment. What do you think if i'll remove this module from github_rotation.tf and i'll just keep resource "aws_iam_role_policy_attachment" "github_token_policy_attachment" {
  role       = "sandbox-test-codepipeline-role"
  policy_arn = aws_iam_policy.github_token_policy.arn
}
in policy_attachment.tf file?

2024-10-11 17:51 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai

2024-10-11 22:42 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  ]
@coderabbitai Doesn't it follow best practice using the depends_on block?

2024-10-12 16:30 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
should be resolved, check please

2024-10-12 16:30 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
should be resolved, check please

2024-10-12 16:30 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
should be resolved, check please

2024-10-12 16:30 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
should be resolved, check please

2024-10-12 16:30 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
should be resolved, check please

2024-10-12 16:31 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
I refactored this file according another your suggestions, check if i can resolve this conversation

2024-10-12 16:35 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai

2024-10-12 16:35 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
@coderabbitai

2024-10-12 16:35 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai

2024-10-12 16:35 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
@coderabbitai

2024-10-12 16:35 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
@coderabbitai

2024-10-12 16:35 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
@coderabbitai

2024-10-22 12:23 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/variables.tf
> +}
There is no longer this variable, check and tell me if I can resolve this conversation.

2024-10-22 12:28 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/variables.tf
> +}
@coderabbitai

2024-10-22 12:36 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  ]
@coderabbitai This depends_on block ensures that resources are created in the correct order

2024-10-22 12:38 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
@coderabbitai

2024-10-22 13:01 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/variables.tf
> +}
@coderabbitai
1. We will leave these variables as they are.
2. Everything has been updated.
3. Here is also everything fine
4. Variables have descriptions

2024-10-22 13:07 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +          }
@coderabbitai, Why do you suggest adding GITHUB_TOKEN if the repo is not private and storing the token in a variable isn't secure?

2024-10-22 13:13 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai All privileges are needed

2024-10-22 13:20 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
no, don't remove the previous tutorial on implementing least privilege in IAM policies. But here it is the minimum we need

2024-10-22 13:20 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai

2024-10-22 13:34 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        ]
variables are defined, I'll also use variables instead of hardcoded "sandbox-test"

2024-10-22 14:07 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/variables.tf
> +}
@coderabbitai there is already another variable

2024-10-22 14:11 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/main.tf
> +}
Do you think we should add a custom KMS? Secrets Manager has encryption by default

2024-10-22 14:11 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/main.tf
> +}
@coderabbitai

2024-10-22 14:16 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai review this file, I refactored it

2024-10-22 14:25 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai check this file, i refactored it

2024-10-22 14:26 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai check this file, i refactored it

2024-10-22 14:40 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github_token/main.tf
> +}
@coderabbitai still bad format?

2024-10-22 14:44 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai, i refactored it check please

2024-10-22 14:44 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai, i refactored it check please

2024-10-22 15:04 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
@coderabbitai I refactored this file, check it, please

2024-10-22 15:05 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
@coderabbitai I refactored this file, check it, please

2024-10-22 15:05 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
@coderabbitai I refactored this file, check it, please

2024-10-22 15:09 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github_token/main.tf
> +      },
@coderabbitai There is already another code, can I resolve this conversation?

2024-10-22 15:11 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai Are you sure we need to add this comment, because there are no comments in other files?

2024-10-22 15:27 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/variables.tf
> +}
@coderabbitai file has been refactored, check it

2024-10-22 15:32 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai There is already another code, check, please.

2024-10-22 15:33 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai , the file already has an empty line at the end of the file

2024-10-22 15:42 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +
@coderabbitai , i retrieve this variable in the buildspec and then use it in the script

2024-10-22 15:47 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +locals {
@coderabbitai , check file should be good now

2024-10-22 16:10 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/policy_attachment.tf
> +}
@coderabbiai i think it isn't a good practice to add comments here, because we don't have comments in other files

2024-10-22 16:13 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/main.tf
> +}
@coderabbitai secrets manager has encryption by default

2024-10-22 16:15 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai , the format should be good now

2024-10-22 16:16 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          aws-region: eu-central-1
@coderabbiai , I added this, check, please

2024-10-22 16:18 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai , I added an empty line at the end of the file.

2024-10-22 17:08 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai show me this suggestion, please

2024-10-22 17:11 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai are you sure this is a good practice to define this variable in the same file?

2024-10-22 17:13 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/policy_attachment.tf
> +}
@coderabbiai i think it isn't a good practice to add comments here, because we don't have comments in other files

2024-10-22 17:20 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/outputs.tf
> +}
@coderabbitai format should be good now

2024-10-22 17:21 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +          }
@coderabbitai , I think TF_VAR is also good because it shows that this is a terraform variable

2024-10-22 20:19 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +data "aws_region" "current" {}
@coderabbitai should be resolved, check, please

2024-10-22 20:21 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai comment is duplicated, you already wrote this suggestion

2024-10-22 20:59 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai show me this suggestion to follow DRY principle, please

2024-10-22 21:05 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
@coderabbitai let's keep it as it is, I think it is a better practice

2024-10-23 09:58 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    if ! gh pr comment "$PR_NUMBER" -R "$GITHUB_REPOSITORY" --body "Latest Version is ready: http://$PROJECT_NAME-$BRANCH_NAME.s3-website.$AWS_DEFAULT_REGION.amazonaws.com"; then
@coderabbitai , no, the correct variant is to use a dot (.)

2024-10-23 10:03 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai there is a mistake Invalid escape sequence: The symbol "." is not a valid escape sequence selector.

2024-10-23 10:05 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +fi
@coderabbitai should be resolved

2024-10-23 13:57 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
@coderabbitai , file should be good now, check it please

2024-10-23 14:06 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai , there are all the variables that we need, is there anything else I should change?

2024-10-23 14:07 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai , resolved, check please

2024-10-23 14:07 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai , resolved, check please

2024-10-23 14:07 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai , resolved, check please

2024-10-23 15:33 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/main.tf
> +
@coderabbiai how does this variable look for you?
variable "github_actions_role_name" {
  description = "Name of the IAM role to be used by the project"
  type        = string
  default     = "github-actions-role" 
}

2024-10-23 16:29 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +      contents: read
@coderabbitai i'll keep it, we have ubuntu-latest in all our yml files

2024-10-23 16:31 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai , i already have this variable

2024-10-23 16:39 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +      - 'sudo apt install gh -y'
@coderabbitai , i think it isn't a good idea to add comment here, so let's keep it as it is

2024-10-23 16:51 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +      }
@coderabbitai all actions are related to different services, so how do you want to combine them here?

2024-10-23 17:12 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +
@coderabbitai these 2 IAM roles related to sandbox deletion

2024-10-23 20:14 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +      identifiers = ["arn:aws:iam::${local.account_id}:role/sandbox-${var.environment}-codepipeline-role"]
@coderabbitai , are you sure it is a good practice to use variable that we are going to use only there?

2024-10-23 20:17 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +      "arn:aws:secretsmanager:${data.aws_region.current.id}:${local.account_id}:secret:github-token"
@coderabbitai file already refactored, check it, please

2024-10-23 20:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai should be resolved

2024-10-23 20:33 UTC, bra1n2h commented on .github/github_token_rotation.md
> +Step-by-Step Guide
@coderabbitai should be resolved

2024-10-23 20:33 UTC, bra1n2h commented on .github/github_token_rotation.md
> +SECRET_NAME	- The name of the secret in AWS Secrets Manager where the GitHub token will be stored. Default is github-token.
@coderabbitai should be resolved

2024-10-23 20:33 UTC, bra1n2h commented on .github/github_token_rotation.md
> +
@coderabbitai should be resolved

2024-10-23 20:36 UTC, bra1n2h commented on .github/github_token_rotation.md
> +    Add the ARN of this role to the role-to-assume field in the workflow.
@coderabbitai should be resolved

2024-10-23 20:36 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +
@coderabbitai should be resolved

2024-10-23 20:36 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
@coderabbitai should be resolved

2024-10-23 20:36 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai should be resolved

2024-10-23 20:37 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai should be resolved

2024-10-23 20:38 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai should be resolved

2024-10-23 20:38 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai should be resolved

2024-10-23 20:42 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai should be resolved

2024-10-23 20:42 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +fi
@coderabbitai should be resolved

2024-10-23 20:42 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/main.tf
> +  name        = "GitHubTokenSecretsAccessPolicy"
@coderabbitai should be resolved

2024-10-23 20:42 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/main.tf
> +
@coderabbitai should be resolved

2024-10-23 20:46 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai token rotation has cron, all errors have error handling mechanism

2024-10-23 20:47 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai temporary file is a bad practice

2024-10-23 20:49 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +
@coderabbitai that whole file related to token rotation, that's why I used this string

2024-10-23 20:51 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai should be resolved

2024-10-23 20:51 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +        Resource = "*"
@coderabbitai should be resolved

2024-10-23 20:52 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +      identifiers = ["arn:aws:iam::${local.account_id}:role/sandbox-${var.environment}-codepipeline-role"]
@coderabbitai should be resolved

2024-10-23 20:52 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          aws-region: ${{ secrets.AWS_REGION }}
@coderabbitai should be resolved

2024-10-23 20:52 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai should be resolved

2024-10-23 21:01 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          aws-region: ${{ secrets.AWS_REGION }}
@coderabbitai should be resolved

2024-10-23 21:01 UTC, bra1n2h commented on .github/workflows/github-token-rotation.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai should be resolved

2024-10-23 21:01 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    echo "Pull request comment created successfully."
@coderabbitai should be resolved

2024-10-23 21:01 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +fi
@coderabbitai should be resolved

2024-10-23 21:02 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +      identifiers = ["arn:aws:iam::${local.account_id}:role/sandbox-${var.environment}-codepipeline-role"]
@coderabbitai should be resolved

2024-10-23 21:03 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +    }
@coderabbitai should be resolved

2024-10-23 21:03 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +      "arn:aws:secretsmanager:${data.aws_region.current.id}:${local.account_id}:secret:github-token*"
@coderabbitai should be resolved

2024-10-23 21:03 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +        "TEST_REPORTS_BUCKET"           = module.test_reports_bucket.id
@coderabbitai should be resolved

2024-10-23 21:03 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +      }
@coderabbitai should be resolved

2024-10-23 21:08 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai it is modules not resources , we have outputs in aws/modules files related to these resources

2024-10-23 21:09 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai should be resolved

2024-10-23 21:11 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +}
@coderabbitai we have value in this variable , file doesn't need to be refactored

2024-10-23 21:12 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +  }
@coderabbitai we use github repo as a source, that's why we use this type and location

2024-10-23 21:14 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +      "arn:aws:secretsmanager:${data.aws_region.current.id}:${local.account_id}:secret:github-token*"
@coderabbitai should be resolved

2024-10-23 21:14 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +        "TEST_REPORTS_BUCKET"           = module.test_reports_bucket.id
@coderabbitai should be resolved

2024-10-23 21:20 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +    }
@coderabbitai should be resolved

2024-10-23 21:20 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +        "TEST_REPORTS_BUCKET"           = module.test_reports_bucket.id
@coderabbitai should be resolved

2024-10-23 21:20 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +      }
@coderabbitai should be resolved

2024-10-23 22:14 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai i will add tags , but rotation rules not needed because we have github actions file for automation token rotation

2024-10-23 22:17 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +        "WEBSITE_GIT_REPOSITORY_LINK"   = "https://github.com/${var.source_repo_owner}/${var.website_content_repo_name}",
@coderabbitai i'll add commas and remove duplicated golang version, that's all we need

2024-10-23 22:42 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai I'll add same changes as in github-token-rotation-prod.yml

2024-10-23 23:17 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +}
@coderabbitai should be resolved

2024-10-23 23:17 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +      "arn:${data.aws_partition.current.partition}:secretsmanager:${data.aws_region.current.id}:${local.account_id}:secret:github-token*"
@coderabbitai should be resolved

2024-10-23 23:17 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/main.tf
> +  name        = var.policy_name
@coderabbitai should be resolved

2024-10-23 23:17 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/variables.tf
> +}
@coderabbitai should be resolved

2024-10-23 23:19 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai should be resolved

2024-10-23 23:19 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai should be resolved

2024-10-23 23:19 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai should be resolved

2024-10-23 23:19 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +done
@coderabbitai should be resolved

2024-10-23 23:21 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +
@coderabbitai should be resolved

2024-10-23 23:21 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +
@coderabbitai should be resolved

2024-10-23 23:21 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +
@coderabbitai should be resolved

2024-10-23 23:21 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          pip3 install PyJWT
@coderabbitai should be resolved

2024-10-23 23:23 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          pip3 install PyJWT
@coderabbitai should be resolved

2024-10-23 23:24 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +
@coderabbitai should be resolved

2024-10-23 23:24 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +
@coderabbitai should be resolved

2024-10-23 23:25 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai should be resolved

2024-10-23 23:25 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +
@coderabbitai should be resolved

2024-10-23 23:25 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +
@coderabbitai should be resolved

2024-10-23 23:25 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +
@coderabbitai should be resolved

2024-10-23 23:27 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +
@coderabbitai should be resolved

2024-10-23 23:31 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/variables.tf
> +}
@coderabbitai i'll keep the value as it is, also a description that you suggested

2024-10-23 23:32 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai i'll keep it to avoid potential errors

2024-10-23 23:32 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai i'll keep it to avoid potential errors

2024-10-23 23:34 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          fi
@coderabbitai you suggested this code

2024-10-23 23:34 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai , error message looks clear , i'll keep it

2024-10-23 23:35 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +  workflow_dispatch: {}
@coderabbitai i'll keep it as it is

2024-10-23 23:36 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +    ]
@coderabbitai all permissions are required

2024-10-23 23:37 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +  }
@coderabbitai all permissions are required

2024-10-23 23:38 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/variables.tf
> +}
@coderabbitai i'll keep the value as it is, also a description that you suggested

2024-10-23 23:39 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai , error message looks clear , i'll keep it

2024-10-23 23:39 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +  workflow_dispatch: {}
@coderabbitai , i'll keep it

2024-10-23 23:40 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +  }
@coderabbitai , all permissions are required

2024-10-23 23:45 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> +        "GOLANG_VERSION"                         = var.runtime_versions.golang,
@coderabbitai there is comma

2024-10-23 23:56 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          fi
@coderabbiai show me the whole file the way you want it to look

2024-10-24 00:01 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          fi
@coderabbitai show me the whole file the way you want it to look

2024-10-24 00:06 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          fi
@coderabbit make note that github-token-rotation-test will be the same and i think we don't need to add env variables

2024-10-24 00:13 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/variables.tf
> +}
@coderabbitai should be resolved

2024-10-24 00:13 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/main.tf
> +  }
@coderabbitai should be resolved

2024-10-24 00:13 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai should be resolved

2024-10-24 00:17 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai should be resolved

2024-10-24 00:17 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +
@coderabbitai should be resolved

2024-10-24 00:17 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          fi
@coderabbitai should be resolved

2024-10-24 00:20 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai should be resolved

2024-10-24 00:20 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai should be resolved

2024-10-24 00:20 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai should be resolved

2024-10-24 00:24 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai should be resolved

2024-10-24 00:24 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai should be resolved

2024-10-24 00:24 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +
@coderabbitai should be resolved

2024-10-24 00:24 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          echo "GitHub token rotated and updated in AWS Secrets Manager."
@coderabbitai should be resolved

2024-10-24 14:32 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          echo "GitHub token has been rotated and updated in AWS Secrets Manager."
@coderabbitai , i asked you to send me file that you want to see, full complete here your comment https://github.com/VilnaCRM-Org/website-infrastructure/pull/5#discussion_r1814008313
why do you ask me to refactor it?

2024-10-24 14:37 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          echo "GitHub token has been rotated and updated in AWS Secrets Manager."
@coderabbitai , also i asked you to make a note that github-token-rotation-prod.yml should be the same as 
github-token-rotation-test.yml

2024-10-24 14:54 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/main.tf
> +      }
@coderabbitai restricted condition is not needed

2024-10-24 14:57 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/variables.tf
> +}
@coderabbitai let's keep it, because it is clearly defined

2024-10-24 15:14 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/variables.tf
> +}
@coderabbitai description i'll keep

2024-10-24 15:14 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai we already discussed it in the recent comment

2024-10-24 15:17 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai , you suggested me add something every commit why can't you add all the required information after 1 commit?

2024-10-24 15:24 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai you suggest refactoring condition block for every commit can you please provide the final variant that satisfies you

2024-10-24 15:28 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai , i'll keep validation as is

2024-10-24 15:31 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai , let's keep validation as is

2024-10-24 15:32 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +
@coderabbiai , error message is clear , let's keep it

2024-10-24 15:39 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +
@coderabbitai , let's keep this error message

2024-10-24 15:41 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          echo "GitHub token has been rotated and updated in AWS Secrets Manager."
@coderabbitai , token expiration is not needed, because we have GitHub actions for rotation

2024-10-24 15:42 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai since values are stored in secrets let's keep this validation

2024-10-24 15:50 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai , are you sure this is a good practice?

2024-10-24 15:53 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          echo "GitHub token has been rotated and updated in AWS Secrets Manager."
@coderabbitai from this suggestion i'll use 1st , 2nd , 3rd.

2024-10-24 15:57 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai Since we use variable in secrets what would be better to use in uses block

2024-10-24 16:22 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai , okay , i'll keep this code then

2024-10-24 16:55 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai , validation doesn't satisfy my needs, i'll remove all validations and keep it in mind

2024-10-24 17:06 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , if i use module.codestar_connection.arn instead of * i got this error Unable to use Connection: arn:aws:codeconnections:eu-central-1:058264240327:connection/9019ca37-49ef-4c15-9cc4-29ae2576aab1. The provided role does not have sufficient permissions.

2024-10-24 17:15 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , yes , i've already tried to specify exact arn and it didn't help

2024-10-24 20:00 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai are you sure all configurations are included?

2024-10-24 20:07 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai I see that you created files in the aws/modules directory for buckets and roles but I can't see policies that were in my file

2024-10-24 20:54 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , are you sure this policy will be attached to our roles?
Also review structure new modules should be in aws/modules and so on in proper directories

2024-10-24 21:01 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai help me please to add new modules in proper directories

2024-10-24 23:23 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          echo "GitHub token has been rotated and updated in AWS Secrets Manager."
@coderabbitai should be resolved

2024-10-24 23:23 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai should be resolved

2024-10-24 23:23 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +
@coderabbitai should be resolved

2024-10-24 23:24 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai should be resolved

2024-10-24 23:25 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai should be resolved

2024-10-24 23:30 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +
@coderabbitai should be resolved

2024-10-25 01:12 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/main.tf
> +  #checkov:skip=CKV2_AWS_57:Token rotation is performed by GitHub actions
@coderabbitai we won't use kms key for this resource

2024-10-25 01:13 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/main.tf
> +  }
@coderabbitai adding documentation in code looks like not a good practice I won't add it

2024-10-25 01:14 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai I'll change only description, we won't add validation for variables

2024-10-25 01:15 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai I won't add validation for variables

2024-10-25 01:15 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai this is 3rd comment according to this line, I'll keep it to avoid potential errors

2024-10-25 01:20 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai also description includes all information that describes variable itself, so l'll keep it also

2024-10-25 01:22 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/variables.tf
> +}
@coderabbitai description is clearly defined and validation I won't add as we discussed earlier

2024-10-25 01:23 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai I'll keep this description because we describe variable and not permissions required

2024-10-25 01:23 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +
@coderabbitai I'll keep this description because we describe variable and not permissions required

2024-10-25 11:13 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/main.tf
> +resource "aws_secretsmanager_secret" "github_token" {
@coderabbitai secret name should be static

2024-10-25 11:24 UTC, bra1n2h commented on terraform/app/modules/aws/iam/policies/github-token/variables.tf
> +}
@coderabbitai , I'll set the description value to this description = "Name of the IAM policy for GitHub token access." since the rest part is related to validation, but we don't have it

2024-10-25 22:39 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          echo "GitHub token has been rotated and updated in AWS Secrets Manager."
@coderabbiai This validation is not needed since we have Github actions for token rotation

2024-10-25 22:42 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai which validation is better because you added 2 of them related to 1 code
this one 
-            echo "Error: VILNACRM_APP_ID and VILNACRM_APP_PRIVATE_KEY must be set in secrets."
+            if [ -z "${{ secrets.VILNACRM_APP_ID }}" ]; then
+              echo "Error: VILNACRM_APP_ID is not set in secrets."
+            fi
+            if [ -z "${{ secrets.VILNACRM_APP_PRIVATE_KEY }}" ]; then
+              echo "Error: VILNACRM_APP_PRIVATE_KEY is not set in secrets."
+            fi

Or another that you specified in this comment?

2024-10-25 22:43 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          echo "GitHub token has been rotated and updated in AWS Secrets Manager."
@coderabbitai This validation is not needed since we have Github actions for token rotation

2024-10-25 22:50 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai or will it be better to use both 1st that I provided and then that is in this comment?

2024-10-25 23:26 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          fi
@coderabbitai now it looks good, isn't it?
      - name: Validate Environment Variables
        run: |
          if [ -z "${{ secrets.VILNACRM_APP_ID }}" ] || [ -z "${{ secrets.VILNACRM_APP_PRIVATE_KEY }}" ]; then
            if [ -z "${{ secrets.VILNACRM_APP_ID }}" ]; then
              echo "Error: VILNACRM_APP_ID is not set in secrets."
            fi
            if [ -z "${{ secrets.VILNACRM_APP_PRIVATE_KEY }}" ]; then
              echo "Error: VILNACRM_APP_PRIVATE_KEY is not set in secrets."
            fi
          fi

2024-10-25 23:30 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai , i combined 2 validations check them they should look fine
      - name: Validate Environment Variables
        run: |
          if [ -z "${{ secrets.VILNACRM_APP_ID }}" ] || [ -z "${{ secrets.VILNACRM_APP_PRIVATE_KEY }}" ]; then
            if [ -z "${{ secrets.VILNACRM_APP_ID }}" ]; then
              echo "Error: VILNACRM_APP_ID is not set in secrets."
            fi
            if [ -z "${{ secrets.VILNACRM_APP_PRIVATE_KEY }}" ]; then
              echo "Error: VILNACRM_APP_PRIVATE_KEY is not set in secrets."
            fi
          fi
          
          # Validate App ID format (should be numeric)
          if ! [[ "${{ secrets.VILNACRM_APP_ID }}" =~ ^[0-9]+$ ]]; then
            echo "Error: VILNACRM_APP_ID should be a numeric value."
            exit 1
          fi
          # Validate private key format (should start with -----BEGIN)
          if ! echo "${{ secrets.VILNACRM_APP_PRIVATE_KEY }}" | grep -q "^-----BEGIN"; then
            echo "Error: VILNACRM_APP_PRIVATE_KEY should be in PEM format."
            exit 1
          fi

2024-10-25 23:41 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai do you remember that github-token-rotation-test.yml should be the same as github-token-rotation-prod.yml ?

2024-10-25 23:52 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +
@coderabbitai i already told you that we are using just github actions file

2024-10-25 23:53 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          fi
@coderabbitai i already told you that we are using gothub actions for token rotation, we don't need this validation for broken expiration

2024-10-26 00:05 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +            ${{ runner.os }}-pip-
@coderabbitai let's remove caching for this moment

2024-10-26 14:25 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          echo "GitHub token has been rotated and updated in AWS Secrets Manager."
@coderabbitai should I add a new step to do this cleanup?

2024-10-26 14:48 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          echo "GitHub token has been rotated and updated in AWS Secrets Manager."
@coderabbitai how does this cleanup look for you?
      - name: Cleanup
        run: |
          # List and revoke old tokens
          old_tokens=$(curl -s \
          -H "Authorization: Bearer $NEW_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/installation/token")

          # Keep only the most recent token
          echo "$old_tokens" | jq -r '.token_ids[]' | \
          while read -r token_id; do
            if [ "$token_id" != "$(echo "$token_response" | jq -r '.id')" ]; then
              curl -s -X DELETE \
              -H "Authorization: Bearer $NEW_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/installation/token/$token_id"
            fi
          done

2024-10-26 15:10 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai I've tried to add code in the new modules that you provided but I got errors. So can you help me please add code to new modules and then use them in stack sandbox_deletion.tf. But keep the functionality of this code that is currently present in the file.

2024-10-26 15:19 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , looks good, but let's follow best practices and define policies in another proper directory, also use different flies for variables and outputs, don't define them in main.tf it's a bad practice

2024-10-26 15:59 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai show me content of new policy module

2024-10-26 17:19 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai this isn't right policy file, I was talking about these policies
resource "aws_iam_role_policy" "codepipeline_restricted_access" {
  name = "codepipeline-restricted-access-policy"
  role = aws_iam_role.codepipeline_role_sandbox.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = [
          "codepipeline:StartPipelineExecution",
          "codepipeline:PutJobSuccessResult",
          "codepipeline:PutJobFailureResult",
          "codepipeline:GetPipelineState",
          "codepipeline:GetPipelineExecution",
          "codepipeline:GetPipeline",
          "codepipeline:ListPipelineExecutions",
          "codepipeline:ListPipelines"
        ]
        Resource = "*"
      },
      {
        Effect   = "Allow"
        Action   = [
          "codebuild:StartBuild",
          "codebuild:BatchGetBuilds",
          "codebuild:ListBuilds",
          "codebuild:ListProjects",
          "codebuild:BatchGetProjects"
        ]
        Resource = "*"
      },
      {
        Effect   = "Allow"
        Action   = [
          "s3:PutObject",
          "s3:GetObject",
          "s3:ListBucket",
          "s3:DeleteObject"
        ]
        Resource = "*"
      }
    ]
  })
}

# CodeBuild Policy
resource "aws_iam_role_policy" "codebuild_policy" {
  name = "codebuild-policy"
  role = aws_iam_role.codebuild_role_sandbox.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = "codestar-connections:UseConnection"
        Resource = var.codestar_connection_arn
      },
      {
        Effect   = "Allow"
        Action   = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = "arn:aws:logs:${var.region}:${var.account_id}:log-group:/aws/codebuild/*"
      }
    ]
  })
}

so we need to create separate folder in modules/aws/iam/policies folder , then policy attachment file, variables file and outputs file. Help me please to add proper content in these files. Also attach these policies to our new roles resource "aws_iam_role" "codebuild_role_sandbox"  and "aws_iam_role_policy" "codepipeline_restricted_access"

2024-10-26 17:36 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , i think i can create them like this in one file:
resource "aws_iam_role_policy" "codepipeline_restricted_access" {
  name = "codepipeline-restricted-access-policy"
  role = aws_iam_role.codepipeline_role_sandbox.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = [
          "codepipeline:StartPipelineExecution",
          "codepipeline:PutJobSuccessResult",
          "codepipeline:PutJobFailureResult",
          "codepipeline:GetPipelineState",
          "codepipeline:GetPipelineExecution",
          "codepipeline:GetPipeline",
          "codepipeline:ListPipelineExecutions",
          "codepipeline:ListPipelines"
        ]
        Resource = "*"
      },
      {
        Effect   = "Allow"
        Action   = [
          "codebuild:StartBuild",
          "codebuild:BatchGetBuilds",
          "codebuild:ListBuilds",
          "codebuild:ListProjects",
          "codebuild:BatchGetProjects"
        ]
        Resource = "*"
      },
      {
        Effect   = "Allow"
        Action   = [
          "s3:PutObject",
          "s3:GetObject",
          "s3:ListBucket",
          "s3:DeleteObject"
        ]
        Resource = "*"
      }
    ]
  })
}

resource "aws_iam_role_policy" "codebuild_policy" {
  name = "codebuild-policy"
  role = aws_iam_role.codebuild_role_sandbox.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = "codestar-connections:UseConnection"
        Resource = var.codestar_connection_arn
      },
      {
        Effect   = "Allow"
        Action   = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = "arn:aws:logs:${var.region}:${var.account_id}:log-group:/aws/codebuild/*"
      }
    ]
  })
}
Then I'll create a variables file and outputs file 
and then in role directory I'll create policy attachment file
After these steps I'll use these module in stack 
so show me this approach from your hand

2024-10-26 22:20 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai about codebuild module, we already have configuration in  codebuild/project/main.tf

2024-10-26 22:26 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , according to this information , what steps should I follow to refactor my sandbox_deletion.tf and have codebuild stages in my new codepipeline? Don't forget that we refactor sandbox_deletion.tf according to the DRY pripnciple

2024-10-28 23:20 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , file was refactored into according DRY principle

2024-10-30 03:00 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-deletion-role/policy.tf
> +}
@coderabbitai , i won't add these policies because we follow at least privilege principle

2024-10-30 11:57 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-deletion-role/policy.tf
> +      }
@coderabbitai i specified exact bucket arn, but I won't remove DeleteBucket policy since we need it

2024-10-30 11:57 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-deletion-role/policy.tf
> +      },
@coderabbitai i specified exact bucket arn, but I won't remove DeleteBucket policy since we need it

2024-10-30 13:32 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox-deletion/main.tf
> +  }
@coderabbitai we don't need to add this block, because we use default encryption for s3 buckets

2024-10-30 14:13 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox-deletion/main.tf
> +  }
@coderabbitai, I already added environment variables to codebuild, because adding them to both resources is not a good practice. I think we don't need this suggestion

2024-10-30 14:45 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/variables.tf
> +}
@coderabbitai , i changed this variables to this one 
variable "logs_bucket_arn" {
  description = "Name of the S3 bucket where CodeBuild logs will be stored"
  type        = string
  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$", var.logs_bucket_name))
    error_message = "S3 bucket name must be between 3 and 63 characters, contain only lowercase letters, numbers, dots, and hyphens, and start/end with a letter or number"
  }
}

so I need to refactor description and validation

2024-10-30 14:58 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +  }
@coderabbiai , using https isn't a good practice. I'll keep this location

2024-10-30 14:59 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +    }
@coderabbitai , we'll keep this variable uppercase because we use this variable as environment in codebuild

2024-10-30 15:03 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +  }
@coderabbitai , using https isn't a good practice. I'll keep this location

2024-10-30 15:27 UTC, bra1n2h commented on terraform/app/modules/aws/s3/sandbox-deletion/main.tf
> +}
@coderabbitai we use encryption by default and logging and versioning are not needed

2024-10-30 15:34 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +}
@coderabbitai , yes show me please this refactoring but also  don't forget about existing module usage that located here terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf

2024-10-30 23:04 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +}
@coderabbitai , i got your opinion, but my file follows your suggestion and best practices, that's why I disagree with this refactoring

2024-10-30 23:04 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , show me this refactoring

2024-10-30 23:35 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai show me modifying the code to reuse the existing CodeBuild configurations

2024-10-30 23:58 UTC, bra1n2h commented on .github/github_token_rotation.md
> +    Integration: This setup integrates with both GitHub and AWS services, ensuring secure storage and usage of tokens.
@coderabbitai , we have 5 comments according the documentation so check please this refactored file, if it looks good now

# GitHub Token Rotation

## Overview

This documentation guides you through the configuration of a GitHub Actions workflow that automates the rotation of a GitHub token. The workflow uses a GitHub App to generate a new GitHub token and stores it securely in AWS Secrets Manager. It is designed to run on a weekly schedule or can be triggered manually. This setup ensures that sensitive tokens are regularly refreshed to maintain security best practices.

### Why Token Rotation is Important

1. **Security**: Regular token rotation reduces the risk of unauthorized access due to potential token leaks or compromises.
2. **Compliance**: Many security standards require regular rotation of credentials to comply with security and compliance regulations.
3. **Automation**: Automating the process eliminates manual errors and simplifies the maintenance of secure tokens.
4. **Integration**: This setup securely integrates GitHub and AWS services, ensuring safe storage and controlled usage of tokens.

---

## Setting Up GitHub Token Rotation Workflow

### Step-by-Step Guide

1. **GitHub Repository Configuration**

   Configure necessary secrets in your GitHub repository for secure AWS and GitHub integration:

   - Navigate to **Settings > Secrets and Variables > Actions** in your GitHub repository.
   - Add the following secrets:
     - `GITHUB_TOKEN_ROTATION_ROLE_TO_ASSUME_TEST`: The ARN of the AWS role for token rotation.
     - `AWS_REGION`: AWS region for Secrets Manager.
     - `VILNACRM_APP_ID`: GitHub App ID (found under **Settings > Applications > Configure your GitHub App > App Settings**).
     - `VILNACRM_APP_PRIVATE_KEY`: GitHub App private key (generated in App settings and stored securely).

2. **GitHub App Configuration**

   Configure a GitHub App to manage repository access:

   - Go to **Settings > Developer Settings > GitHub Apps** and select **New GitHub App**.
   - Fill out the required fields and configure permissions:
     - **Administration**: Unnecessary, can be removed for security.
     - **Metadata**: Read-only (essential for basic API access).
     - **Contents**: Read-only (required for workflow operations).
   - Generate and store a private key securely.
   - Install the GitHub App on the intended repository.

3. **Workflow Schedule Configuration**

   This workflow is set to rotate the token every Sunday at midnight (0 0 * * 0) and can be manually triggered using `workflow_dispatch`.

   - To modify the schedule, adjust the cron expression under `schedule` in the YAML file to your preferred rotation frequency.

---

## Testing and Verification Procedures

### Testing Procedures for Sandbox Environment

1. **Set up a sandbox repository** to mimic the production environment.
2. **Add test secrets and necessary permissions** to the sandbox environment.
3. **Trigger the workflow manually** to observe the process in a controlled environment without affecting production.

### Verification of Token Rotation

1. **Validate the new token** in AWS Secrets Manager to confirm successful rotation.
2. **Verify GitHub App access** by querying the API endpoints to ensure the new token works as expected.

### Testing Token Permissions

1. Perform a series of actions allowed by the token in a test environment.
2. Ensure that the token’s permissions are scoped appropriately and that it has the **minimum required access** to perform its functions.

---

## Troubleshooting Guide

### Common Issues and Solutions

1. **Token Generation Failures**: 
   - Ensure the GitHub App has sufficient permissions.
   - Verify that the correct App ID and private key are in use.

2. **AWS Secrets Manager Errors**: 
   - Check AWS permissions for the role in use.
   - Ensure the correct `AWS_REGION` is set and the role ARN has the right policy for Secrets Manager access.

### Debug Procedures

- Use the `DEBUG` flag in the workflow for additional logging output.
- Confirm AWS IAM role assumptions and permissions align with workflow requirements.

---

## Security Best Practices

### Token Usage and Expiration

- Configure tokens with appropriate expiration periods.
- Set the workflow frequency in alignment with token expiration.

### Principle of Least Privilege

- Limit token permissions to the minimum required.
- Remove unnecessary permissions, like **Administration: Read & Write**, as noted.

### Audit Logging

- Enable audit logging in AWS and GitHub to monitor token usage.
- Regularly review access logs for any unusual activity.

### Emergency Rotation Procedures

- If a token is suspected to be compromised, trigger a **manual token rotation** and replace the compromised token in AWS Secrets Manager immediately.

---

## Operational Considerations

### Error Handling and Retry Strategy

- Configure the workflow to automatically retry upon failures due to transient errors.
- Use conditional steps to handle failures gracefully, ensuring no sensitive data is exposed.

### Monitoring and Alerting Setup

- Integrate alerts (e.g., using GitHub Actions or AWS CloudWatch) for failed rotations.
- Set up notifications via Slack, email, or SMS to alert the security team about failures.

### Preventing Concurrent Execution

- Use a **mutex lock** or implement checks to prevent concurrent executions, avoiding race conditions during token updates.

### Backup Procedures for Rotation Failures

- Maintain a secure backup token as a contingency.
- Regularly verify that backup tokens are rotated in sync with the primary rotation schedule.

---

This enhanced workflow aligns permissions with the **principle of least privilege** and automates security compliance through regular, validated token rotations.

2024-10-31 00:19 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-deletion-role/variables.tf
> +}
@coderabbitai , since validation for variables is good practice let's keep it

2024-10-31 00:28 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox-deletion/variables.tf
> +}
@coderabbitai , are you sure this is a good practice to use exact names for region validation?

2024-10-31 00:29 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +  }
@coderabbitai , I already tried to use such a path instead of arn and I encountered errors

2024-10-31 00:36 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +  }
@coderabbitai , these variables we use in bash scripts , I'm not sure that removing region variable is needed

2024-10-31 00:42 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , we have codepipeline/sandbox folder for sandbox creation , that's why I added sandbox-deletion pipeline. What do you think?

2024-10-31 00:48 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +  }
@coderabbitai , I don't think this is a good practice since user can use any branch 'source_version  = "main"'

2024-10-31 15:35 UTC, bra1n2h commented on .github/github_token_rotation.md
> +- **Naming Conventions**: Name tokens with a clear structure (e.g., `github-rotation-token-<timestamp>`) for better audit trails.
@coderabbitai accroding to  the best practice token expiration should be every 7 days

2024-10-31 15:38 UTC, bra1n2h commented on .github/github_token_rotation.md
> +- **Naming Conventions**: Name tokens with a clear structure (e.g., `github-rotation-token-<timestamp>`) for better audit trails.
@coderabbitai why do we need this if we automatically rotate this token every 7 days?

2024-10-31 16:19 UTC, bra1n2h commented on .github/github_token_rotation.md
> +This enhanced workflow aligns permissions with the **principle of least privilege** and automates security compliance through regular, validated token rotations.
@coderabbitai , yes please, provide script to automatically fix these formatting issues

2024-10-31 16:33 UTC, bra1n2h commented on .github/github_token_rotation.md
> +
@coderabbitai , are you sure about this change, I used a script with a prettier, format should be good?

2024-10-31 17:26 UTC, bra1n2h commented on terraform/app/modules/aws/s3/sandbox-deletion/variables.tf
> +}
@coderabbitai , tags are optional variable so I can suggest this validation or remove validation from the tags variable 
validation {
    condition = var.tags == {} || length(var.tags) >= 0
    error_message = "Tags must be a map and can be empty or contain any key-value pairs."
  }

2024-10-31 17:29 UTC, bra1n2h commented on terraform/app/modules/aws/s3/sandbox-deletion/variables.tf
> +}
@coderabbitai , error_message should be updated as well

2024-10-31 17:59 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/variables.tf
> +}
@coderabbitai I think error_message matches with condition, don't you agree?

2024-10-31 18:33 UTC, bra1n2h commented on .github/github_token_rotation.md
> +## Token Configuration and Best Practices
@coderabbitai , i use prettier, so file format should be good

2024-10-31 19:00 UTC, bra1n2h commented on .github/github_token_rotation.md
> +6. [Operational Considerations](#operational-considerations)
@coderabbitai , you provided 2 same lists

2024-10-31 20:57 UTC, bra1n2h commented on .github/github_token_rotation.md
> +```
@coderabbitai format looks not correct  I'll keep command as it is

2024-10-31 21:23 UTC, bra1n2h commented on .github/github_token_rotation.md
> +
@coderabbitai , rotation will be used in different environments, so no need to describe for each
also, all information is in an overview and more detailed in other sections

2024-10-31 21:39 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/variables.tf
> +}
@coderabbitai , do you think this a good practice to use data block in variables file?

2024-10-31 21:50 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox-deletion/variables.tf
> +}
@coderabbitai , since we are going to use this condition
+    condition     = can(regex("^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$", var.s3_bucket_name)) && !can(regex("\\.\\.", var.s3_bucket_name))
we'll also need to change error_message

2024-10-31 22:00 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/variables.tf
> +}
@coderabbitai we discussed region variable, that validation is not needed to allow to use any region

2024-10-31 22:01 UTC, bra1n2h commented on .github/github_token_rotation.md
> +# GitHub Token Rotation
@coderabbitai i use prettier for format as you suggested

2024-10-31 22:01 UTC, bra1n2h commented on .github/github_token_rotation.md
> +     - `GITHUB_TOKEN_ROTATION_ROLE_TO_ASSUME_PROD`: The ARN of the AWS role for token rotation for prod environment.
@coderabbitai we use just 2 variables that's why i added 2 of them

2024-10-31 22:02 UTC, bra1n2h commented on .github/github_token_rotation.md
> +```
@coderabbitai this command is just an example, so user can refactor it as he needs

2024-10-31 22:04 UTC, bra1n2h commented on .github/github_token_rotation.md
> +
@coderabbitai there is already guidance for token rotation

2024-10-31 22:13 UTC, bra1n2h commented on .github/github_token_rotation.md
> +
@coderabbitai do you think this step is needed since adding permissions is manual step?

2024-10-31 22:25 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/variables.tf
> +}
@coderabbitai is this condition     = can(regex("^(?:[\\w-]+/)*[\\w-]+\\.ya?ml$", var.buildspec_path)) the most suitable condition?

2024-10-31 23:38 UTC, bra1n2h commented on terraform/app/modules/aws/s3/sandbox-deletion/outputs.tf
> +}
@coderabbitai , why do we need to add validation in output block if we have validation in variables already?

2024-10-31 23:40 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/variables.tf
> +}
@coderabbitai existing error message says that variable needs to follow GitHub requirements, so any additional information isn't necessary.

2024-10-31 23:43 UTC, bra1n2h commented on terraform/app/modules/aws/s3/sandbox-deletion/outputs.tf
> +}
@coderabbitai output "codepipeline_bucket_name" {
  description = "Name of the S3 bucket used for storing CodePipeline artifacts"
  value       = aws_s3_bucket.codepipeline_bucket.bucket
  
  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9.-]*[a-z0-9]$", var.bucket))
    error_message = "Bucket names must be between 3 and 63 characters long and can contain only lowercase letters, numbers, hyphens, and periods."
  }
} 
You suggested this refactor , I don't have validation in output block

2024-11-01 12:14 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +  }
@coderabbitai , submodules config is not needed since we don't use it in our project

2024-11-01 12:27 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +  }
@coderabbitai ,  retention_in_days = 30 is not expected here , and I'll return source variable type to GITHUB but I'll keep location because using https is not a good practice

2024-11-01 12:55 UTC, bra1n2h commented on terraform/app/modules/aws/codebuild/sandbox-deletion/main.tf
> +
@coderabbitai , you already posted a comment related to this issue, I'll review if it possible to use existing module and I'll let you know, what we going to do in another comment

2024-11-01 12:57 UTC, bra1n2h commented on terraform/app/modules/aws/s3/sandbox-deletion/main.tf
> +}
@coderabbitai , we use default encryption , so this server_side is not needed

2024-11-01 12:57 UTC, bra1n2h commented on terraform/app/modules/aws/s3/sandbox-deletion/main.tf
> +}
@coderabbitai versioning for this bucket is not needed

2024-11-01 12:58 UTC, bra1n2h commented on terraform/app/modules/aws/s3/sandbox-deletion/main.tf
> +}
@coderabbitai , lifecycle configuration for this bucket is not needed

2024-11-01 15:19 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-deletion-role/policy.tf
> +          "arn:aws:codepipeline:${var.region}:${var.account_id}:${var.project_name}-codepipeline-role-sandbox-deletion-${var.environment}"
@coderabbitai , after testing i can say, that i need this policy here

2024-11-01 17:37 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-deletion-role/policy.tf
> +        ]
@coderabbitai , this resource contains policy that codepipeline role needs, that's why it is located here

2024-11-02 22:39 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai, I understand your point. You want me to use an existing CodeBuild configuration. Please help me refactor this file.  Here is the information that you need:
Existing codebuild module: terraform/app/modules/aws/codebuild/stages/main.tf
Code blocks to configure codebuild stages: terraform/app/stacks/ci-cd-infrastructure/locals.tf
Summary: We need to use existing codebuild module, add separate configuration for deletion stage and add module reference in our stack

2024-11-06 18:53 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , show me this refactoring. But make a note, that I already use the existing CodeBuild configuration. So my CodeBuild module has a source like this source  =  "../../modules/aws/codebuild/stages"
Now we need to refactor the CodePipeline module to have a source codepipeline/sandbox.

2024-11-07 13:06 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/variables.tf
> +}
@coderabbitai we already have validation for these variables in another module, are you sure we need to add validation here?

2024-11-07 13:25 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-deletion-role/variables.tf
> +}
@coderabbitai The validation of these variables is well-defined and it does not interfere with the program's operation, since it has been tested

2024-11-07 13:40 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox_deletion.tf
> +}
@coderabbitai , I reuse existing CodeBuild configurations that are located in codebuild/stages/main.tf as we use in sandbox.tf

2024-11-07 14:26 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/tfvars/prod.tfvars
> +]
@coderabbitai , you can see in the project that we have validation in every script and buildspec files to catch configuration issues. We also have healthcheck that is located in ci_cd_website_stage_input. And there is stage Delete for cleanup sandbox.

2024-11-07 14:37 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/tfvars/prod.tfvars
>  ]
@coderabbitai , fronted developers will close or merge PR that will trigger a cleanup. There are stages for codebuild and variables in the file, I didn't get what resource quotas and limits. We have CloudWatch for tracking. Also about the lifetime after testing the developer will trigger deletion. So I didn't understand the purpose of these steps.

2024-11-07 15:01 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/tfvars/prod.tfvars
> +]
@coderabbitai , we already discussed it, that we have checks in scripts and buildspecs that are used for this sandbox environment

2024-11-08 15:01 UTC, Kravalg requested changes

2024-11-08 15:01 UTC, Kravalg commented on terraform/app/stacks/website-sandbox/tfvars/prod.tfvars
> +  Project     = "Sandbox"
Project is vilnacrm, sandbox it is type of the feature

2024-11-08 15:01 UTC, Kravalg commented on terraform/app/stacks/website-sandbox/tfvars/prod.tfvars
> +project_name = "sandbox-prod"
Project name is vilnacrm

2024-11-08 15:01 UTC, Kravalg commented on terraform/app/stacks/website-sandbox/tfvars/test.tfvars
> +project_name = "sandbox-test"
Project name is vilnacrm

2024-11-08 15:01 UTC, Kravalg commented on terraform/app/stacks/website-sandbox/tfvars/test.tfvars
> +  Project     = "Sandbox"
Why do we need project when we have project name ?

2024-11-11 13:59 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +      - 'sudo apt install gh -y'
@coderabbitai sandbox can be created and deleted multiple times to test new features and changes, when deleted the entire infrastructure disappears completely, so what's the reason to remove this installation if after deletion everything is created from scratch?

2024-11-11 14:05 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +      - 'bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pull_request.sh'
@coderabbitai what is the purpose of creating such a non-informational error handler when our script has error handling at every step of its execution and has more precise information?

2024-11-11 14:22 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +done
@coderabbitai I don't understand why add "Expected format" because the check here is whether the variable is set or not

2024-11-11 15:28 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +      - 'bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pull_request.sh'
@coderabbitai I studied the code you proposed and I don't understand why it is needed in the code build if we already have logs connected there for debugging

2024-11-11 15:36 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    fi
@coderabbitai , we have validation for these variables, they can't include special characters

2024-11-11 15:37 UTC, bra1n2h commented on aws/scripts/sh/create_pull_request.sh
> +    COMMENT_BODY="Latest Version is ready: http://$PROJECT_NAME-$BRANCH_NAME.s3-website.$AWS_DEFAULT_REGION.amazonaws.com"
@coderabbitai , we have validation for this variable, it can't include special characters

2024-11-11 15:43 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +      - 'bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pull_request.sh'
@coderabbitai what is the purpose of creating such a non-informational error handler when our script has error handling at every step of its execution and has more precise information?

2024-11-11 16:07 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +      - 'sudo apt install gh -y'
@coderabbitai This version of the GitHub CLI allows you to use the latest updates and makes it easier to maintain CI/CD without updating versions manually.

2024-11-11 18:25 UTC, bra1n2h commented on Makefile
> +	$(CHMOD) +x codebuild_build.sh
@coderabbitai , I didn't understand why should we remove the script using: `$(RM) -f codebuild_build.sh`, if we are going to use it for local testing after installation?

2024-11-11 18:29 UTC, bra1n2h commented on Makefile
> +	$(CHMOD) +x codebuild_build.sh
@coderabbitai no, there is no removal command for codebuild_build.sh. But you recommended to add it, I don't understand why if we execute codebuild-local-set-up , to have this script locally?

2024-11-11 18:44 UTC, bra1n2h commented on Makefile
> +	$(TFENV) use 1.4.7
@coderabbitai your command for error handling isn't correct this should be better ./install-opentofu.sh --install-method rpm || { $(ECHO) "Failed to install OpenTofu" && exit 1; }

2024-11-12 13:01 UTC, bra1n2h commented on Makefile
> +	$(TFENV) use $(TERRAFORM_VERSION)
@coderabbitai why is the error handling syntax incorrect?

2024-11-12 14:33 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/sandbox.tf
> +  s3_artifacts_bucket_files_deletion_days = var.s3_artifacts_bucket_files_deletion_days
@Kravalg, this variable is located along this path terraform/app/stacks/ci-cd-infrastructure/tfvars/base.tfvars and set to the 7 days

2024-11-12 15:01 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-deletion-role/variables.tf
> +}
@coderabbitai explain me please why do you think my validation won't accept 'ap-southeast-3' ?

2024-11-13 13:51 UTC, bra1n2h commented on aws/scripts/sh/create_pr_comment.sh
> +
@coderabbitai using a variable here will make this script unworkable

2024-11-13 13:52 UTC, bra1n2h commented on aws/scripts/sh/create_pr_comment.sh
> +done
@coderabbitai validation is not needed here because we have validation in variables.tf files

2024-11-13 13:58 UTC, bra1n2h commented on aws/scripts/sh/create_pr_comment.sh
> +
@coderabbitai thank you for this clarification. I'll change the error message to reflect that the token is retrieved from AWS Secrets Manager.

2024-11-13 14:02 UTC, bra1n2h commented on aws/scripts/sh/create_pr_comment.sh
> +
@coderabbitai , i don't understand the purpose of adding this function since everything in our COMMENT_BODY variable is the same

2024-11-13 14:08 UTC, bra1n2h commented on aws/scripts/sh/create_pr_comment.sh
> +
@coderabbitai , our infrastructure is based on these variables developers need to define them for each PR and branch they want to test

2024-11-13 19:03 UTC, bra1n2h commented on aws/scripts/sh/rotate_github_token.sh
> +))
@coderabbitai , I'll change these variables in validation

2024-11-13 19:09 UTC, bra1n2h commented on aws/scripts/sh/rotate_github_token.sh
> +    os.getenv('VILNACRM_APP_PRIVATE_KEY').replace('\\n', '\n'),
@coderabbitai I added these variables in github-token-rotation-prod.yml as env because we get them from github secrets and get them using os.getenv is this approach good?

2024-11-17 20:09 UTC, bra1n2h commented on aws/buildspecs/website/down.yml
> -      python: $PYTHON_VERSION
Because we are not using python in this buildspec and its installation will increase run time.

2024-11-17 20:10 UTC, bra1n2h commented on aws/buildspecs/website/plan.yml
> -      python: $PYTHON_VERSION
Because we are not using python in this buildspec and its installation will increase run time.

2024-11-17 20:12 UTC, bra1n2h commented on terraform/app/modules/aws/iam/oidc/codepipeline/main.tf
> -  secret_name     = "${upper(var.environment)}_AWS_CODEPIPELINE_NAME"
On this one, if I remember correctly due to that we have two envs staging and production we need different secret names for both of them not to overwrite them. So you will need to change them to include env in the secrets name.

2024-11-17 20:16 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/locals.tf
> -        "PYTHON_VERSION"                         = var.runtime_versions.python,
The purpose of removing this variable was that we don't use this variable in the website plan stage

2024-11-17 20:17 UTC, bra1n2h commented on terraform/app/stacks/website-sandbox/tfvars/test.tfvars
> +  Project     = "Sandbox"
I removed this tag, because it is optional

2024-11-18 14:20 UTC, bra1n2h commented on .github/workflows/super-linter.yml
> +          fetch-depth: 0
@coderabbitai super-linter requires 0

2024-11-18 14:36 UTC, bra1n2h commented on .github/workflows/super-linter.yml
> +          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
@coderabbitai we need all files to follow super-linter rules

2024-11-19 19:11 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +}
@coderabbitai tags are optional and can be any value so validation isn't necessary I think

2024-11-19 19:25 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/variables.tf
> +  }
@coderabbitai I agree that this validation doesn't account for paths within buckets , but it is variable for bucket arn and not for bucket objects

2024-11-19 20:32 UTC, Kravalg requested changes
Please check all my comments again and answer if we had some questions to discuss

2024-11-20 12:23 UTC, bra1n2h commented on .github/workflows/github-token-rotation-prod.yml
> +          set -euo pipefail
I removed this script to a separate file aws/scripts/sh/rotate_github_token.sh

2024-11-20 12:23 UTC, bra1n2h commented on .github/workflows/github-token-rotation-test.yml
> +          set -euo pipefail
I removed this script to a separate file aws/scripts/sh/rotate_github_token.sh

2024-11-20 12:31 UTC, bra1n2h commented on terraform/app/modules/aws/s3/public/main.tf
> +resource "aws_s3_bucket" "bucket" {
I changed this name earlier because coderabbitai suggested it, after your comment I looked at this bucket and I can agree that the bucket name is not understandable, also coderabbitai made a mistake because he compared the resource name and suffixes for buckets that contain "reports-bucket".

2024-11-20 12:33 UTC, bra1n2h commented on terraform/app/modules/aws/codepipeline/sandbox/kms.tf
> +resource "aws_kms_key" "codepipeline_sns_encryption_key" {
I've removed the KMS key usage

2024-11-20 12:41 UTC, bra1n2h commented on aws/scripts/py/s3_sandbox_configuration.py
> +
I reviewed super-linter guidance and discovered that my super-linter doesn't commit fixes.

2024-11-23 15:28 UTC, Kravalg requested changes
It will be enough to check if s3 bucket exists using this command `aws s3api head-bucket` and we don’t need to upload and delete any additional files like marker file

2024-11-23 15:28 UTC, Kravalg commented on aws/buildspecs/sandbox/deploy.yml
> +      - "echo #### Check for bucket creation and decide on PR comment"
It will be better to check if s3 bucket exists, you don’t need to upload marker file and then delete it

2024-11-23 15:28 UTC, Kravalg commented on aws/scripts/sh/sandbox_creation.sh
> +        MARKER_PATH=".markers/bucket_created.txt"
It will be better to check if s3 bucket exists, you don’t need to upload marker file and then delete it

2024-11-25 18:18 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +        }
@coderabbitai how do i need to unset this variable if it doesn't exist?

2024-11-29 14:11 UTC, bra1n2h commented on terraform/app/modules/aws/iam/oidc/pipeline-trigger-role/outputs.tf
> +}
@coderabbitai why do we need to add such output if we don't use it now and this means we won't use it?

2024-12-02 19:08 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai are you sure that we need to add this block here? I read that Terraform does not directly support depends_on at the module level

2024-12-02 19:28 UTC, bra1n2h commented on terraform/app/stacks/ci-cd-infrastructure/github_rotation.tf
> +}
@coderabbitai in our code all module references are configured using local paths

2024-12-23 17:19 UTC, bra1n2h commented on terraform/app/modules/aws/secrets/main.tf
> +}
@coderabbitai lower characters are included by default

2025-01-09 13:16 UTC, bra1n2h commented on aws/buildspecs/sandbox/deploy.yml
> +        }
@coderabbitai bad suggestion since in codebuild phases executes in different shells

2025-01-10 20:12 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/sandbox-codepipeline-role/data.tf
> +  }
@coderabbitai ListSecret doesn't work with exact arns or even with template "arn:aws:secretsmanager:eu-central-1:<account_id>:secret:*"

2025-01-16 20:15 UTC, Kravalg requested changes
Good job

2025-01-16 20:15 UTC, Kravalg commented on .github/workflows/tflint.yml
>          name: Checkout source code
I agree with coderabbit
Please fix this comment

2025-01-17 19:47 UTC, bra1n2h commented on terraform/app/modules/aws/iam/roles/github-token-rotation-role/main.tf
> +}
@coderabbitai explain this suggested change, what should it do?

2025-01-19 16:05 UTC, Kravalg approved these changes
Awesome !

2025-01-19 16:05 UTC, merged